// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockscad.Msg.es');


Blockscad.Msg.ABORT_BUTTON = "Abortar";
Blockscad.Msg.ABOUT_LINK = "Acerca de";
Blockscad.Msg.ACROSS = "a través de";
Blockscad.Msg.ADVANCED_TOOLBOX = "Colección avanzada de bloques";
Blockscad.Msg.ALONG = "a lo largo";
Blockscad.Msg.AROUND = "alrededor de";
Blockscad.Msg.AXES_BUTTON = "Pasar los ejes";
Blockscad.Msg.AXIS = "eje";
Blockscad.Msg.BLOCKS_BUMPED_OUT_DIMENSIONS = "%1 bloques fueron echados: 2D y 3D figuras no pueden estar juntos.";
Blockscad.Msg.BLOCKS_BUMPED_OUT_TYPES = "%1 bloques fueron echados: desajuste de tipo entre %2 y %3";
Blockscad.Msg.BLOCKS_TAB = "Bloques";
Blockscad.Msg.BLOCK_COLORS = "Colores de bloques";
Blockscad.Msg.BLOCK_TEXT_2D = "texto 2D";
Blockscad.Msg.BLOCK_TEXT_3D = "texto 3D";
Blockscad.Msg.BROWSE = "explorar";
Blockscad.Msg.BS_3DTEXT_TOOLTIP = "3D texto con tamaño, fuente, y grosor especificados";
Blockscad.Msg.BS_TEXT_TOOLTIP = "2D texto con tamaño y fuente especificados";
Blockscad.Msg.CATEGORY_2D_SHAPES = "Formas 2D";
Blockscad.Msg.CATEGORY_3D_SHAPES = "Formas 3D";
Blockscad.Msg.CATEGORY_LOGIC = "Lógica";
Blockscad.Msg.CATEGORY_LOOPS = "Secuencias";
Blockscad.Msg.CATEGORY_MATH = "Matemáticas";
Blockscad.Msg.CATEGORY_PROCEDURES = "Funciones";
Blockscad.Msg.CATEGORY_SET_OPERATIONS = "Ops de Conjuntos";
Blockscad.Msg.CATEGORY_TEXT = "Texto";
Blockscad.Msg.CATEGORY_TRANSFORMATIONS = "Transformaciones";
Blockscad.Msg.CATEGORY_VARIBLES = "Variables";
Blockscad.Msg.CENTER = "centro";
Blockscad.Msg.CENTERED = "centrado";
Blockscad.Msg.CHANGE_EMAIL = "Cambiar Correo Electrónico";
Blockscad.Msg.CHANGE_EMAIL_CURRENT = "Viejo Correo";
Blockscad.Msg.CHANGE_EMAIL_NEW = "Nuevo Correo";
Blockscad.Msg.CHANGE_PASSWORD = "Cambiar Contraseña";
Blockscad.Msg.CHANGE_PASSWORD_INSTRUCTIONS = "Después de cambiar su contraseña, BlocksCAD preguntará a reiniciar su sesión.";
Blockscad.Msg.CIRCLE = "circulo";
Blockscad.Msg.CIRCLE_TOOLTIP = "<img src='imgs/en/circle.svg' width='65'>";
Blockscad.Msg.CLASSIC_COLORS = "Clásicos";
Blockscad.Msg.CODE_TAB = "Código";
Blockscad.Msg.COLOR = "color";
Blockscad.Msg.COLOR_HSV_TOOLTIP = "Aplica un color especificando los componentes matiz, saturación, y valor.  Cada valor deberia ser entre 0 y 100.";
Blockscad.Msg.COLOR_HUE = "matiz";
Blockscad.Msg.COLOR_RGB_TOOLTIP = "Aplica un color especificando los componentes rojo, azul, y verde.  Cada valor deberia ser entre 0 y 100.";
Blockscad.Msg.COLOR_SATURATION = "saturación";
Blockscad.Msg.COLOR_TOOLTIP = "Aplica el color al objeto, que debe ser 3D";
Blockscad.Msg.COLOR_VALUE = "valor";
Blockscad.Msg.CONFIRM_DIALOG_NO = "No";
Blockscad.Msg.CONFIRM_DIALOG_YES = "Sí";
Blockscad.Msg.CONFIRM_NEW_PASSWORD = "Reentra Nueva Contraseña";
Blockscad.Msg.CONTROLS_FOR_TOOLTIP_CHAINHULL = "Muestra la envoltura convexa de cada figura en la secuencia con la figura seguida.";
Blockscad.Msg.CONVEX_HULL = "envoltura convexa";
Blockscad.Msg.CUBE = "cubo";
Blockscad.Msg.CUBE_TOOLTIP = "<img src='imgs/en/cube.svg' width='100px'>";
Blockscad.Msg.CYLINDER = "cilindro";
Blockscad.Msg.CYLINDER_TOOLTIP = "<img src='imgs/en/cylinder.svg' width='190px'>";
Blockscad.Msg.DEFAULT_COLOR_BUTTON = "Poner valor por defecto de los colores";
Blockscad.Msg.DELETE_ACCOUNT = "Borrar mi cuenta";
Blockscad.Msg.DELETE_ACCOUNT_BUTTON = "Delete Account and Sign Out";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM = "Are you sure you want to delete your BlocksCAD account?";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM_PASSWORD = "Enter password to confirm";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_ONE = "In about 48 hours your account will be permanently deleted.";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_TWO = "If you change your mind, just sign in to your account within the next 48 hours.";  // untranslated
Blockscad.Msg.DELETE_PROJECT_CONFIRM = "¿Esta seguro que quiere borrar *Project_name*?";
Blockscad.Msg.DIALOG_OR = "o";
Blockscad.Msg.DIAMETER = "diámetro";
Blockscad.Msg.DIFFERENCE = "diferencia";
Blockscad.Msg.DIFFERENCE_TOOLTIP = "Resta uno o más objetos desde el primer objeto en la lista.";
Blockscad.Msg.DIRECTION_BACK = "detrás";
Blockscad.Msg.DIRECTION_BOTTOM = "abajo";
Blockscad.Msg.DIRECTION_DIAGONAL = "diagonal";
Blockscad.Msg.DIRECTION_FRONT = "en frente";
Blockscad.Msg.DIRECTION_LEFT = "izquierda";
Blockscad.Msg.DIRECTION_RIGHT = "derecha";
Blockscad.Msg.DIRECTION_TOP = "cima";
Blockscad.Msg.DISABLE_ALL = "Desactivar todos bloques";
Blockscad.Msg.DISCARD_ALL = "Borrar todos %1 bloques?";
Blockscad.Msg.DOCUMENTATION_LINK = "Documentación";
Blockscad.Msg.EMAIL_FIELD = "Correo Electrónico";
Blockscad.Msg.ENABLE_ALL = "Activar todos bloques";
Blockscad.Msg.ERROR_BAD_PASSWORD = "Incorrect password - please retype your original password.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_EMPTY = "Please enter an email address.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_INVALID = "Su correo electrónico no es valido.";
Blockscad.Msg.ERROR_LOGIN_FAILED = "Nombre de usuario o contraseña incorrecta.";
Blockscad.Msg.ERROR_MESSAGE = "Error";
Blockscad.Msg.ERROR_MISSING_EMAIL = "We can't find this email address.";  // untranslated
Blockscad.Msg.ERROR_MISSING_USERNAME = "We can't find this username.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_CONFIRM = "Su segunda contraseña debe ser igual a su primera contraseña.";
Blockscad.Msg.ERROR_PASSWORD_IS_EMPTY = "Please choose a password at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_PASSWORD = "Your password cannot be the word 'password'.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_USERNAME = "Su contraseña no puede ser igual que su nombre de usuario.";
Blockscad.Msg.ERROR_PASSWORD_LENGTH = "Your password must be at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_USERNAME_CHARACTERS = "Your username may only contain letters, numbers, -, and _";  // untranslated
Blockscad.Msg.ERROR_USERNAME_EXISTS = "Lo sentimos, ese nombre de usuario ya existe.";
Blockscad.Msg.ERROR_USERNAME_IS_EMPTY = "Por favor, elija un nombre de usuario.";
Blockscad.Msg.ERROR_USERNAME_LENGTH = "Username must be between 3 and 30 characters.";  // untranslated
Blockscad.Msg.EXAMPLES_MENU = "Ejemplos";
Blockscad.Msg.EXAMPLE_ANTHIAS_FISH = "pez";
Blockscad.Msg.EXAMPLE_CUBE_WITH_CUTOUTS = "armazón cubo";
Blockscad.Msg.EXAMPLE_LOOP_SINE = "figure do función senoidal hecho en secuencia";
Blockscad.Msg.EXAMPLE_LOOP_SUN = "figura de sol hecho en secuencia";
Blockscad.Msg.EXAMPLE_PARAMETRIC_BOX = "caja de cualquier tamaño";
Blockscad.Msg.EXAMPLE_PARAMETRIC_EQ_KNOT = "nudo de ecuaciones paramétricas";
Blockscad.Msg.FACES = "caras";
Blockscad.Msg.FANCYMIRROR_TOOLTIP = "Refleja uno o más objetos a través de un plano cual vector normal es desde (0,0,0) al punto (x,y,z).";
Blockscad.Msg.FANCYROTATE_TOOLTIP = "Rota uno o más objetos alrededor de un vector desde el origen (0,0,0) al punto (x,y,z)";
Blockscad.Msg.FN_TOOLTIP = "Poner el número de lados usados para aproximar arcos (en esfera, cilindro, circulo, y toro).";
Blockscad.Msg.FONT_NAME = "fuente";
Blockscad.Msg.FONT_SIZE = "tamaño";
Blockscad.Msg.GENERATE_STL = "Generar";
Blockscad.Msg.GET_STARTED_VIDEO = "!Empieza!";
Blockscad.Msg.HEIGHT = "altura";
Blockscad.Msg.HELP_MENU = "Ayuda";
Blockscad.Msg.HIGHLIGHT_INSTANCES = "Destacar '%1' instancias";
Blockscad.Msg.HSV_COLOR_MODEL = "HSV";
Blockscad.Msg.HULL_TOOLTIP = "Combina uno o más objetos envolteandolos juntos en una cápsula.";
Blockscad.Msg.IMPORT_BLOCKS_LOCAL = "Cargar bloques en el proyecto actual";
Blockscad.Msg.IMPORT_STL = "Importar un archivo STL";
Blockscad.Msg.IMPORT_STL_MENU = "Importar el archivo STL al proyecto actual";
Blockscad.Msg.INTERSECTION = "intersección";
Blockscad.Msg.INTERSECTION_TOOLTIP = "Muestra la intersección (area que superpone) de dos o más objetos.";
Blockscad.Msg.LINEAREXTRUDE_TOOLTIP = "Usa una extrusión en uno o más 2D objetos por una altura especificada con una torcion especificada. Figura puede ser escalada mientras extrude en x, y.  Puede ser centrada alrededor del origen.";
Blockscad.Msg.LINEAR_EXTRUDE = "extrusión lineal";
Blockscad.Msg.LOAD_BLOCKS_LOCAL = "Cargar bloques desde su computadora";
Blockscad.Msg.LOGIN_BUTTON = "Iniciar sesión";
Blockscad.Msg.LOGIN_IN_PROGRESS = "Iniciando...";
Blockscad.Msg.LOGOUT_BUTTON = "Salir";
Blockscad.Msg.MINUS = "menos";
Blockscad.Msg.MIRROR = "reflejar";
Blockscad.Msg.MIRROR_ADVANCED = "reflejar por el vector";
Blockscad.Msg.MOUSEOVER_REDO = "Rehacer";
Blockscad.Msg.MOUSEOVER_TRASHCAN = "Borrar todos bloques";
Blockscad.Msg.MOUSEOVER_UNDO = "Deshacer";
Blockscad.Msg.MY_PROJECTS = "Mis proyectos";
Blockscad.Msg.NEW = "Nuevo";
Blockscad.Msg.NEW_PASSWORD = "Nueva Contraseña";
Blockscad.Msg.NEW_PROJECT_BUTTON = "Nuevo proyecto";
Blockscad.Msg.NOT_CENTERED = "no centrado";
Blockscad.Msg.NOT_COMPATIBLE_WITH_OPENSCAD = "No es compatible con OpenSCAD";
Blockscad.Msg.OLD_PASSWORD = "Vieja Contraseña";
Blockscad.Msg.OPTIONS_MENU = "Opciones";
Blockscad.Msg.PALE_COLORS = "Pálidos";
Blockscad.Msg.PARSE_IN_PROGRESS = "Analizando...";
Blockscad.Msg.PARSING_ERROR_ILLEGAL_VALUE = "%1 bloques tienen un valor ilegal (negativo o cero)";
Blockscad.Msg.PARSING_ERROR_MISSING_FIELDS = "a %1 bloques no tienen valores.";
Blockscad.Msg.PASSWORD_FIELD = "Contraseña";
Blockscad.Msg.PASSWORD_FORGOT_FIELD = "¿Olvido su contraseña?";
Blockscad.Msg.PASSWORD_RESET_EMAIL_INSTRUCTIONS = "Un correo electrónico ha sido enviado al correo asociado con su cuenta con un link para reajustar su contraseña.  Si no lo recibes, busquelo en su carpeta de spam";
Blockscad.Msg.PASSWORD_RESET_EMAIL_SENT = "Password Reset Email has been Sent";  // untranslated
Blockscad.Msg.PASSWORD_RETYPE_FIELD = "Reentrar contraseña";
Blockscad.Msg.PLUS = "más";
Blockscad.Msg.PROJECT_LIST_DELETE_BUTTON = "Borrar";
Blockscad.Msg.PROJECT_LIST_EXIT = "Salir de lista";
Blockscad.Msg.PROJECT_LIST_FILTER = "Filtrar";
Blockscad.Msg.PROJECT_LIST_LAST_MODIFIED = "Última modificación";
Blockscad.Msg.PROJECT_LIST_MORE_BUTTON = "Más";
Blockscad.Msg.PROJECT_MENU = "Proyecto";
Blockscad.Msg.PROJECT_NAME = "Nombre de Proyecto";
Blockscad.Msg.PROJECT_NAME_DEFAULT = "Sin título";
Blockscad.Msg.RADIUS = "radio";
Blockscad.Msg.REACTIVATE_ACCOUNT_EXPLAINED = "Su cuenta esta reactivada; ya no será borrada";
Blockscad.Msg.REACTIVATE_ACCOUNT_TITLE = "Su cuenta no será borrada";
Blockscad.Msg.REACTIVATE_BUTTON = "Okay";
Blockscad.Msg.REGISTER_BUTTON = "Registrar";
Blockscad.Msg.REGISTER_IN_PROGRESS = "Registrando...";
Blockscad.Msg.REGISTER_NEW_USER = "Registrar Nuevo Usuario";
Blockscad.Msg.REMOVE_BLOCK_HIGHLIGHTING = "Quitar destaco de bloques";
Blockscad.Msg.REMOVE_HIGHLIGHTING_INSTANCES = "Quitar destaco";
Blockscad.Msg.RENDER_BUTTON = "Hacer";
Blockscad.Msg.RENDER_ERROR_EMPTY = "Vacío";
Blockscad.Msg.RENDER_ERROR_MIXED = "No se pueden mezclar objetos 2D y 3D.";
Blockscad.Msg.RENDER_IN_PROGRESS = "Haciendo...";
Blockscad.Msg.REPORT_ISSUE = "Reportar problema";
Blockscad.Msg.RESET_PASSWORD = "Reset Password";  // untranslated
Blockscad.Msg.RESET_PASSWORD_INSTRUCTIONS = "Enter your username or your email and we will send you an email with instructions to reset your password.";  // untranslated
Blockscad.Msg.RESET_PASSWORD_LINK_BUTTON = "Send me a link to reset my password!";  // untranslated
Blockscad.Msg.RESET_VIEW_BUTTON = "Reiniciar vista";
Blockscad.Msg.RGB_COLOR_MODEL = "RGB";
Blockscad.Msg.ROTATE = "rotar";
Blockscad.Msg.ROTATEEXTRUDE_TOOLTIP = "Extrusión por rotación uno o más 2D objetos alrededor del Z eje con un número especificado de lados.";
Blockscad.Msg.ROTATE_ADVANCED = "rotar por el vector";
Blockscad.Msg.ROTATE_EXTRUDE = "extrusión por rotación";
Blockscad.Msg.SAVE_BLOCKS_AS_COPY = "Guardar como copia";
Blockscad.Msg.SAVE_BLOCKS_LOCAL = "Guardar bloques en tu computadora";
Blockscad.Msg.SAVE_BUTTON = "Guardar";
Blockscad.Msg.SAVE_COMPLETE = "¡Guardado!";
Blockscad.Msg.SAVE_FAILED = "No Pudo Guardar";
Blockscad.Msg.SAVE_FAILED_PROJECT_NAME = "Entra un nombre a su proyecto y vuelve a intentar.";
Blockscad.Msg.SAVE_IN_PROGRESS = "Guardando...";
Blockscad.Msg.SAVE_PROMPT = "¿Desea guardar su proyecto?";
Blockscad.Msg.SAVE_PROMPT_NO = "No guardar";
Blockscad.Msg.SAVE_PROMPT_YES = "Guardar";
Blockscad.Msg.SAVE_SCAD_LOCAL = "Guardar el programa OpenSCAD en su computadora";
Blockscad.Msg.SCALE = "escala";
Blockscad.Msg.SCALE_TOOLTIP = "Escala uno o más objetos por la cantidad en x, y, z.";
Blockscad.Msg.SIDES = "aristas";
Blockscad.Msg.SIMPLEMIRROR_TOOLTIP = "Refleja uno o más objetos a través del plano.";
Blockscad.Msg.SIMPLEROTATE_TOOLTIP = "Rota uno o más objetos en x, y, z.";
Blockscad.Msg.SIMPLE_TOOLBOX = "Colección simple de bloques";
Blockscad.Msg.SPHERE = "esfera";
Blockscad.Msg.SPHERE_TOOLTIP = "<img src='imgs/en/sphere.svg' width='65'>";
Blockscad.Msg.SQUARE = "cuadrado";
Blockscad.Msg.SQUARE_TOOLTIP = "<img src='imgs/en/square.svg' width='65'>";
Blockscad.Msg.STL_IMPORT_WARNING = "Archivos STL no estan guardados con los bloques.";
Blockscad.Msg.TAPER = "afilar";
Blockscad.Msg.TAPER_TOOLTIP = "Escala figuras por un eje.  El valor más pequeño por el eje esta escalado a uno, y el valor más grande esta escalado a el valor elegido.";
Blockscad.Msg.TEXT_DEFAULT_VALUE = "abc";
Blockscad.Msg.TEXT_THICKNESS = "grosor";
Blockscad.Msg.TORUS = "toro";
Blockscad.Msg.TORUS_TOOLTIP = "<img src='imgs/en/torus.svg' width='540px'>";
Blockscad.Msg.TRANSLATE = "trasladar";
Blockscad.Msg.TRANSLATE_TOOLTIP = "Traslada (mueve) uno o más objetos en x, y, z.";
Blockscad.Msg.TWIST = "torcer";
Blockscad.Msg.UNION = "unión";
Blockscad.Msg.UNION_TOOLTIP = "Combina dos o más objetos para formar uno.";
Blockscad.Msg.USERNAME_FIELD = "Nombre de usuario";
Blockscad.Msg.VARIABLES_BUMPED_ONE = "%1 bloques variables fueron echados por desajuste de tipo";
Blockscad.Msg.VARIABLES_BUMPED_TWO = "variable '%1': tipo cambiado desde %2 a %3";
Blockscad.Msg.WARNING_RELOAD_STL = "Advertencia: vuelva a cargar su archivo STL";
Blockscad.Msg.WITH = "con";
Blockscad.Msg.ZOOM_IN_BUTTON = "Zoom +";
Blockscad.Msg.ZOOM_OUT_BUTTON = "Zoom -";
Blockscad.Msg.ZOOM_RESET_BUTTON = "Reiniciar vista";
