// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockscad.Msg.ja');


Blockscad.Msg.ABORT_BUTTON = "中止";
Blockscad.Msg.ABOUT_LINK = "概要";
Blockscad.Msg.ACROSS = "軸";
Blockscad.Msg.ADVANCED_TOOLBOX = "フルメニュー";
Blockscad.Msg.ALONG = "方向";
Blockscad.Msg.AROUND = "回転軸";
Blockscad.Msg.AXES_BUTTON = "表示軸の切り替え";
Blockscad.Msg.AXIS = "軸";
Blockscad.Msg.BLOCKS_BUMPED_OUT_DIMENSIONS = "%1個のブロックを配置できません。2Dと3Dのオブジェクトを同時に使用できません";
Blockscad.Msg.BLOCKS_BUMPED_OUT_TYPES = "%1個のブロックを配置できません。%2と%3の形式が不整合です";
Blockscad.Msg.BLOCKS_TAB = "ブロック";
Blockscad.Msg.BLOCK_COLORS = "ブロックカラー";
Blockscad.Msg.BLOCK_TEXT_2D = "2Dテキスト";
Blockscad.Msg.BLOCK_TEXT_3D = "3Dテキスト";
Blockscad.Msg.BROWSE = "ブラウザ";
Blockscad.Msg.BS_3DTEXT_TOOLTIP = "任意の高さ、フォント、厚さでの3Dテキストを作成";
Blockscad.Msg.BS_TEXT_TOOLTIP = "任意の高さとフォントの2Dテキストを作成";
Blockscad.Msg.CATEGORY_2D_SHAPES = "2D";
Blockscad.Msg.CATEGORY_3D_SHAPES = "3D";
Blockscad.Msg.CATEGORY_LOGIC = "関数";
Blockscad.Msg.CATEGORY_LOOPS = "繰り返し";
Blockscad.Msg.CATEGORY_MATH = "数値";
Blockscad.Msg.CATEGORY_PROCEDURES = "モジュール";
Blockscad.Msg.CATEGORY_SET_OPERATIONS = "オプション";
Blockscad.Msg.CATEGORY_TEXT = "テキスト";
Blockscad.Msg.CATEGORY_TRANSFORMATIONS = "修正";
Blockscad.Msg.CATEGORY_VARIBLES = "変数";
Blockscad.Msg.CENTER = "原点";
Blockscad.Msg.CENTERED = "中心原点";
Blockscad.Msg.CHANGE_EMAIL = "Change Email";  // untranslated
Blockscad.Msg.CHANGE_EMAIL_CURRENT = "Current Email";  // untranslated
Blockscad.Msg.CHANGE_EMAIL_NEW = "New Email";  // untranslated
Blockscad.Msg.CHANGE_PASSWORD = "パスワードを変更";
Blockscad.Msg.CHANGE_PASSWORD_INSTRUCTIONS = "パスワードを変更した場合、再度ログインが必要です";
Blockscad.Msg.CIRCLE = "円";
Blockscad.Msg.CIRCLE_TOOLTIP = "<img src='imgs/en/circle.svg' width='140'>";
Blockscad.Msg.CLASSIC_COLORS = "デフォルト";
Blockscad.Msg.CODE_TAB = "コード";
Blockscad.Msg.COLOR = "色";
Blockscad.Msg.COLOR_HSV_TOOLTIP = "HSV値を0～100の間で指定して色を変更";
Blockscad.Msg.COLOR_HUE = "H色相";
Blockscad.Msg.COLOR_RGB_TOOLTIP = "RGB値を0～100の間で指定して色を変更";
Blockscad.Msg.COLOR_SATURATION = "S彩度";
Blockscad.Msg.COLOR_TOOLTIP = "3Dオブジェクトの色を変更";
Blockscad.Msg.COLOR_VALUE = "V明度";
Blockscad.Msg.CONFIRM_DIALOG_NO = "キャンセル";
Blockscad.Msg.CONFIRM_DIALOG_YES = "はい";
Blockscad.Msg.CONFIRM_NEW_PASSWORD = "新しいパスワードを確認";
Blockscad.Msg.CONTROLS_FOR_TOOLTIP_CHAINHULL = "後のオブジェクトで指定された繰り返し内の包含オブジェクトを返す";
Blockscad.Msg.CONVEX_HULL = "包含";
Blockscad.Msg.CUBE = "立方体";
Blockscad.Msg.CUBE_TOOLTIP = "<img src='imgs/en/cube.svg' width='100px'>";
Blockscad.Msg.CYLINDER = "円柱";
Blockscad.Msg.CYLINDER_TOOLTIP = "<img src='imgs/en/cylinder.svg' width='190px'>";
Blockscad.Msg.DEFAULT_COLOR_BUTTON = "レンダリングのデフォルト色を設定";
Blockscad.Msg.DELETE_ACCOUNT = "Delete My Account";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_BUTTON = "Delete Account and Sign Out";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM = "Are you sure you want to delete your BlocksCAD account?";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM_PASSWORD = "Enter password to confirm";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_ONE = "In about 48 hours your account will be permanently deleted.";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_TWO = "If you change your mind, just sign in to your account within the next 48 hours.";  // untranslated
Blockscad.Msg.DELETE_PROJECT_CONFIRM = "*Project_name*を削除してよろしいですか?";
Blockscad.Msg.DIALOG_OR = "または";
Blockscad.Msg.DIAMETER = "直径";
Blockscad.Msg.DIFFERENCE = "差";
Blockscad.Msg.DIFFERENCE_TOOLTIP = "一つ目のオブジェクトからひとつまたは、複数のオブジェクトを差し引く";
Blockscad.Msg.DIRECTION_BACK = "後面";
Blockscad.Msg.DIRECTION_BOTTOM = "下面";
Blockscad.Msg.DIRECTION_DIAGONAL = "鳥瞰";
Blockscad.Msg.DIRECTION_FRONT = "正面";
Blockscad.Msg.DIRECTION_LEFT = "左";
Blockscad.Msg.DIRECTION_RIGHT = "右";
Blockscad.Msg.DIRECTION_TOP = "上面";
Blockscad.Msg.DISABLE_ALL = "すべてのブロックを無効化";
Blockscad.Msg.DISCARD_ALL = "%1個のブロックをすべて削除しますか？";
Blockscad.Msg.DOCUMENTATION_LINK = "Documentation";
Blockscad.Msg.EMAIL_FIELD = "メールアドレス";
Blockscad.Msg.ENABLE_ALL = "すべてのブロックを有効化";
Blockscad.Msg.ERROR_BAD_PASSWORD = "Incorrect password - please retype your original password.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_EMPTY = "Please enter an email address.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_INVALID = "正しいメールアドレスを入力してください";
Blockscad.Msg.ERROR_LOGIN_FAILED = "ユーザー名またはパスワードが間違っています";
Blockscad.Msg.ERROR_MESSAGE = "エラー";
Blockscad.Msg.ERROR_MISSING_EMAIL = "We can't find this email address.";  // untranslated
Blockscad.Msg.ERROR_MISSING_USERNAME = "We can't find this username.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_CONFIRM = "確認のため一つ目と同じパスワードを再入力してください";
Blockscad.Msg.ERROR_PASSWORD_IS_EMPTY = "Please choose a password at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_PASSWORD = "Your password cannot be the word 'password'.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_USERNAME = "パスワードが間違っています";
Blockscad.Msg.ERROR_PASSWORD_LENGTH = "Your password must be at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_USERNAME_CHARACTERS = "Your username may only contain letters, numbers, -, and _";  // untranslated
Blockscad.Msg.ERROR_USERNAME_EXISTS = "このユーザー名はすでに使用されています";
Blockscad.Msg.ERROR_USERNAME_IS_EMPTY = "ユーザー名を入力してください";
Blockscad.Msg.ERROR_USERNAME_LENGTH = "Username must be between 3 and 30 characters.";  // untranslated
Blockscad.Msg.EXAMPLES_MENU = "作例";
Blockscad.Msg.EXAMPLE_ANTHIAS_FISH = "熱帯魚";
Blockscad.Msg.EXAMPLE_CUBE_WITH_CUTOUTS = "立方体フレーム";
Blockscad.Msg.EXAMPLE_LOOP_SINE = "正弦波";
Blockscad.Msg.EXAMPLE_LOOP_SUN = "繰り返しによる太陽";
Blockscad.Msg.EXAMPLE_PARAMETRIC_BOX = "立方体";
Blockscad.Msg.EXAMPLE_PARAMETRIC_EQ_KNOT = "等式の飾り結び";
Blockscad.Msg.FACES = "面";
Blockscad.Msg.FANCYMIRROR_TOOLTIP = "任意の座標点を起点にオブジェクトを反転";
Blockscad.Msg.FANCYROTATE_TOOLTIP = "任意の座標点を中心にオブジェクトを回転";
Blockscad.Msg.FN_TOOLTIP = "球、円柱、ドーナツにおいて、弧のラスター数を指定して曲線表示解像度を変更";
Blockscad.Msg.FONT_NAME = "フォント";
Blockscad.Msg.FONT_SIZE = "高さ";
Blockscad.Msg.GENERATE_STL = "ファイルを作成";
Blockscad.Msg.GET_STARTED_VIDEO = "はじめる";
Blockscad.Msg.HEIGHT = "高さ";
Blockscad.Msg.HELP_MENU = "ヘルプ";
Blockscad.Msg.HIGHLIGHT_INSTANCES = "'%1'をハイライト";
Blockscad.Msg.HSV_COLOR_MODEL = "HSV";
Blockscad.Msg.HULL_TOOLTIP = "複数のオブジェクトを包含したグループを作成";
Blockscad.Msg.IMPORT_BLOCKS_LOCAL = "ファイルを現在のプロジェクトに配置";
Blockscad.Msg.IMPORT_STL = "STL出力";
Blockscad.Msg.IMPORT_STL_MENU = "STLファイルを現在のプロジェクトに配置";
Blockscad.Msg.INTERSECTION = "交差";
Blockscad.Msg.INTERSECTION_TOOLTIP = "複数のオブジェクトの重複部分を求める";
Blockscad.Msg.LINEAREXTRUDE_TOOLTIP = "2Dオブジェクトを任意の角度まで、X、Y方向とも尺度変更死ながら押し出し。中心原点も選択可能";
Blockscad.Msg.LINEAR_EXTRUDE = "押し出し";
Blockscad.Msg.LOAD_BLOCKS_LOCAL = "ファイルの読み込み";
Blockscad.Msg.LOGIN_BUTTON = "ログイン";
Blockscad.Msg.LOGIN_IN_PROGRESS = "ログイン中...";
Blockscad.Msg.LOGOUT_BUTTON = "ログアウト";
Blockscad.Msg.MINUS = "引く";
Blockscad.Msg.MIRROR = "反転";
Blockscad.Msg.MIRROR_ADVANCED = "自由反転";
Blockscad.Msg.MOUSEOVER_REDO = "やり直す";
Blockscad.Msg.MOUSEOVER_TRASHCAN = "クリア";
Blockscad.Msg.MOUSEOVER_UNDO = "戻る";
Blockscad.Msg.MY_PROJECTS = "マイプロジェクト";
Blockscad.Msg.NEW = "新規作成";
Blockscad.Msg.NEW_PASSWORD = "新しいパスワード";
Blockscad.Msg.NEW_PROJECT_BUTTON = "新規プロジェクト";
Blockscad.Msg.NOT_CENTERED = "原点";
Blockscad.Msg.NOT_COMPATIBLE_WITH_OPENSCAD = "OpenSCADでは使用できません";
Blockscad.Msg.OLD_PASSWORD = "現在のパスワード";
Blockscad.Msg.OPTIONS_MENU = "オプション";
Blockscad.Msg.PALE_COLORS = "淡色";
Blockscad.Msg.PARSE_IN_PROGRESS = "読み込み中...";
Blockscad.Msg.PARSING_ERROR_ILLEGAL_VALUE = "%1個のブロックの数値が無効です";
Blockscad.Msg.PARSING_ERROR_MISSING_FIELDS = "%1個のブロックの数値がありません";
Blockscad.Msg.PASSWORD_FIELD = "パスワード";
Blockscad.Msg.PASSWORD_FORGOT_FIELD = "パスワードを忘れた";
Blockscad.Msg.PASSWORD_RESET_EMAIL_INSTRUCTIONS = "We've sent an email to the address associated with your account with a link to reset your password. If you don't see it, check your spam folder";  // untranslated
Blockscad.Msg.PASSWORD_RESET_EMAIL_SENT = "パスワードをリセットするためのメールを送信しました";
Blockscad.Msg.PASSWORD_RETYPE_FIELD = "パスワードを再度入力してください";
Blockscad.Msg.PLUS = "足す";
Blockscad.Msg.PROJECT_LIST_DELETE_BUTTON = "削除";
Blockscad.Msg.PROJECT_LIST_EXIT = "プロジェクトに戻る";
Blockscad.Msg.PROJECT_LIST_FILTER = "フィルター";
Blockscad.Msg.PROJECT_LIST_LAST_MODIFIED = "最後の更新";
Blockscad.Msg.PROJECT_LIST_MORE_BUTTON = "その他";
Blockscad.Msg.PROJECT_MENU = "プロジェクト";
Blockscad.Msg.PROJECT_NAME = "プロジェクト名";
Blockscad.Msg.PROJECT_NAME_DEFAULT = "名称未設定";
Blockscad.Msg.RADIUS = "半径";
Blockscad.Msg.REACTIVATE_ACCOUNT_EXPLAINED = "アカウントは再有効化されました。削除されません";
Blockscad.Msg.REACTIVATE_ACCOUNT_TITLE = "アカウントは削除されません";
Blockscad.Msg.REACTIVATE_BUTTON = "Okay";
Blockscad.Msg.REGISTER_BUTTON = "登録";
Blockscad.Msg.REGISTER_IN_PROGRESS = "登録中...";
Blockscad.Msg.REGISTER_NEW_USER = "新規ユーザー登録";
Blockscad.Msg.REMOVE_BLOCK_HIGHLIGHTING = "ブロックのハイライトを削除";
Blockscad.Msg.REMOVE_HIGHLIGHTING_INSTANCES = "ハイライトを削除";
Blockscad.Msg.RENDER_BUTTON = "レンダリング";
Blockscad.Msg.RENDER_ERROR_EMPTY = "コードがありません";
Blockscad.Msg.RENDER_ERROR_MIXED = "2Dオブジェクトと3Dオブジェクトがあります。どちらかのみ入力してください";
Blockscad.Msg.RENDER_IN_PROGRESS = "レンダリング中...";
Blockscad.Msg.REPORT_ISSUE = "問題を報告";
Blockscad.Msg.RESET_PASSWORD = "Reset Password";  // untranslated
Blockscad.Msg.RESET_PASSWORD_INSTRUCTIONS = "Enter your username or your email and we will send you an email with instructions to reset your password.";  // untranslated
Blockscad.Msg.RESET_PASSWORD_LINK_BUTTON = "Send me a link to reset my password!";  // untranslated
Blockscad.Msg.RESET_VIEW_BUTTON = "ビューをリセット";
Blockscad.Msg.RGB_COLOR_MODEL = "RGB";
Blockscad.Msg.ROTATE = "回転";
Blockscad.Msg.ROTATEEXTRUDE_TOOLTIP = "Z軸を中心に2Dオブジェクトを任意の側面数で回転押し出し";
Blockscad.Msg.ROTATE_ADVANCED = "自由回転";
Blockscad.Msg.ROTATE_EXTRUDE = "回転押し出し";
Blockscad.Msg.SAVE_BLOCKS_AS_COPY = "別名で保存";
Blockscad.Msg.SAVE_BLOCKS_LOCAL = "保存ファイルをダウンロード";
Blockscad.Msg.SAVE_BUTTON = "保存";
Blockscad.Msg.SAVE_COMPLETE = "保存しました";
Blockscad.Msg.SAVE_FAILED = "保存済";
Blockscad.Msg.SAVE_FAILED_PROJECT_NAME = "プロジェクト名を指定してください";
Blockscad.Msg.SAVE_IN_PROGRESS = "保存中...";
Blockscad.Msg.SAVE_PROMPT = "プロジェクトを保存しますか？";
Blockscad.Msg.SAVE_PROMPT_NO = "保存しない";
Blockscad.Msg.SAVE_PROMPT_YES = "保存";
Blockscad.Msg.SAVE_SCAD_LOCAL = "OpenSCADコードをコンピュータに保存";
Blockscad.Msg.SCALE = "尺度変更";
Blockscad.Msg.SCALE_TOOLTIP = "X、Y、Zそれぞれの方向の尺度を変更";
Blockscad.Msg.SIDES = "曲線表示解像度";
Blockscad.Msg.SIMPLEMIRROR_TOOLTIP = "オブジェクトを任意の平面をはさんで反転";
Blockscad.Msg.SIMPLEROTATE_TOOLTIP = "オブジェクトをX、Y、Z軸を中心に回転";
Blockscad.Msg.SIMPLE_TOOLBOX = "簡易メニュー";
Blockscad.Msg.SPHERE = "球";
Blockscad.Msg.SPHERE_TOOLTIP = "<img src='imgs/en/sphere.svg' width='140'>";
Blockscad.Msg.SQUARE = "矩形";
Blockscad.Msg.SQUARE_TOOLTIP = "<img src='imgs/en/square.svg' width='65'>";
Blockscad.Msg.STL_IMPORT_WARNING = "STLファイルが保存されていません";
Blockscad.Msg.TAPER = "テーパー";
Blockscad.Msg.TAPER_TOOLTIP = "選択した座標軸の尺度を1、それ以外の座標軸の尺度を入力数とする";
Blockscad.Msg.TEXT_DEFAULT_VALUE = "abc";
Blockscad.Msg.TEXT_THICKNESS = "厚さ";
Blockscad.Msg.TORUS = "ドーナツ";
Blockscad.Msg.TORUS_TOOLTIP = "<img src='imgs/en/torus.svg' width='540px'>";
Blockscad.Msg.TRANSLATE = "移動";
Blockscad.Msg.TRANSLATE_TOOLTIP = "オブジェクトをX、Y、Zの任意の方向に移動";
Blockscad.Msg.TWIST = "ねじれ";
Blockscad.Msg.UNION = "和";
Blockscad.Msg.UNION_TOOLTIP = "複数のオブジェクトをひとつに結合";
Blockscad.Msg.USERNAME_FIELD = "ユーザー名";
Blockscad.Msg.VARIABLES_BUMPED_ONE = "%1個の変数ブロックの形式が合わないため配置できませんでした";
Blockscad.Msg.VARIABLES_BUMPED_TWO = "変数'%1':%2から%3に変更されました";
Blockscad.Msg.WARNING_RELOAD_STL = "警告:STLファイルを再ロードしてください";
Blockscad.Msg.WITH = "と";
Blockscad.Msg.ZOOM_IN_BUTTON = "ズームイン";
Blockscad.Msg.ZOOM_OUT_BUTTON = "ズームアウト";
Blockscad.Msg.ZOOM_RESET_BUTTON = "ビューをリセット";
