// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockscad.Msg.pl');


Blockscad.Msg.ABORT_BUTTON = "Przerwij";
Blockscad.Msg.ABOUT_LINK = "O programie";
Blockscad.Msg.ACROSS = "poprzecznie";
Blockscad.Msg.ADVANCED_TOOLBOX = "Zaawansowane Narzędzia";
Blockscad.Msg.ALONG = "wzdłóż";
Blockscad.Msg.AROUND = "wzdłóż";
Blockscad.Msg.AXES_BUTTON = "Przełącz widok osi";
Blockscad.Msg.AXIS = "oś";
Blockscad.Msg.BLOCKS_BUMPED_OUT_DIMENSIONS = "%1 calling blocks were displaced: 2D and 3D shapes cannot be together";  // untranslated
Blockscad.Msg.BLOCKS_BUMPED_OUT_TYPES = "%1 calling blocks were displaced: type mismatch between %2 and %3";  // untranslated
Blockscad.Msg.BLOCKS_TAB = "Bloki";
Blockscad.Msg.BLOCK_COLORS = "Schemat Kolorów Bloków";
Blockscad.Msg.BLOCK_TEXT_2D = "Tekst 2D";
Blockscad.Msg.BLOCK_TEXT_3D = "Tekst 3D";
Blockscad.Msg.BROWSE = "przeglądaj";
Blockscad.Msg.BS_3DTEXT_TOOLTIP = "Tekst 3D w danym rozmiarze, z rodzajem czcionki i o wyznaczonej grubości.";
Blockscad.Msg.BS_TEXT_TOOLTIP = "Tekst 2D w danym rozmiarze i rodzajem czcionki";
Blockscad.Msg.CATEGORY_2D_SHAPES = "Kształty 2D";
Blockscad.Msg.CATEGORY_3D_SHAPES = "Kształty 3D";
Blockscad.Msg.CATEGORY_LOGIC = "Logiczne";
Blockscad.Msg.CATEGORY_LOOPS = "Pętle";
Blockscad.Msg.CATEGORY_MATH = "Matematyczne";
Blockscad.Msg.CATEGORY_PROCEDURES = "Moduły";
Blockscad.Msg.CATEGORY_SET_OPERATIONS = "Set Ops";  // untranslated
Blockscad.Msg.CATEGORY_TEXT = "Tekst";
Blockscad.Msg.CATEGORY_TRANSFORMATIONS = "Przekształcenia";
Blockscad.Msg.CATEGORY_VARIBLES = "Zmienne";
Blockscad.Msg.CENTER = "środek";
Blockscad.Msg.CENTERED = "wyśrodkowane";
Blockscad.Msg.CHANGE_EMAIL = "Change Email";  // untranslated
Blockscad.Msg.CHANGE_EMAIL_CURRENT = "Current Email";  // untranslated
Blockscad.Msg.CHANGE_EMAIL_NEW = "New Email";  // untranslated
Blockscad.Msg.CHANGE_PASSWORD = "Change Password";  // untranslated
Blockscad.Msg.CHANGE_PASSWORD_INSTRUCTIONS = "After changing your password, BlocksCAD will prompt you to login again.";  // untranslated
Blockscad.Msg.CIRCLE = "koło";
Blockscad.Msg.CIRCLE_TOOLTIP = "<img src='imgs/en/circle.svg' width='65'>";
Blockscad.Msg.CLASSIC_COLORS = "Klasyczny";
Blockscad.Msg.CODE_TAB = "Kod";
Blockscad.Msg.COLOR = "kolor";
Blockscad.Msg.COLOR_HSV_TOOLTIP = "Nadaj kolor podając wartości dla odcienia, saturacji i jasności (HSV). Wartości pomiędzy 0 a 100.";
Blockscad.Msg.COLOR_HUE = "odcień";
Blockscad.Msg.COLOR_RGB_TOOLTIP = "Nadaj kolor podając wartości dla czerwieni, niebieskiego i zielonego (RGB). Wartości pomiędzy 0 a 100.";
Blockscad.Msg.COLOR_SATURATION = "saturacja";
Blockscad.Msg.COLOR_TOOLTIP = "Nadaje kolor obiektom 3D.";
Blockscad.Msg.COLOR_VALUE = "jasność";
Blockscad.Msg.CONFIRM_DIALOG_NO = "Przerwij";
Blockscad.Msg.CONFIRM_DIALOG_YES = "Tak";
Blockscad.Msg.CONFIRM_NEW_PASSWORD = "Retype New Password";
Blockscad.Msg.CONTROLS_FOR_TOOLTIP_CHAINHULL = "Tworzy otoczkę wypukłą obiektów z kolejnym obiektem w pętli";
Blockscad.Msg.CONVEX_HULL = "otoczka";
Blockscad.Msg.CUBE = "sześcian";
Blockscad.Msg.CUBE_TOOLTIP = "<img src='imgs/en/cube.svg' width='100px'>";
Blockscad.Msg.CYLINDER = "cylinder";
Blockscad.Msg.CYLINDER_TOOLTIP = "<img src='imgs/en/cylinder.svg' width='90px'>";
Blockscad.Msg.DEFAULT_COLOR_BUTTON = "Ustaw domyślny kolor renderowania";
Blockscad.Msg.DELETE_ACCOUNT = "Delete My Account";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_BUTTON = "Delete Account and Sign Out";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM = "Are you sure you want to delete your BlocksCAD account?";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM_PASSWORD = "Enter password to confirm";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_ONE = "In about 48 hours your account will be permanently deleted.";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_TWO = "If you change your mind, just sign in to your account within the next 48 hours.";  // untranslated
Blockscad.Msg.DELETE_PROJECT_CONFIRM = "Czy napewno SKASOWAĆ *Project_name*?";
Blockscad.Msg.DIALOG_OR = "lub";
Blockscad.Msg.DIAMETER = "średnica";
Blockscad.Msg.DIFFERENCE = "odejmij";
Blockscad.Msg.DIFFERENCE_TOOLTIP = "Odejmuje jeden lub wiele obiektów od pierwszego obiektu z tej listy.";
Blockscad.Msg.DIRECTION_BACK = "tył";
Blockscad.Msg.DIRECTION_BOTTOM = "spód";
Blockscad.Msg.DIRECTION_DIAGONAL = "ukośny";
Blockscad.Msg.DIRECTION_FRONT = "przód";
Blockscad.Msg.DIRECTION_LEFT = "lewo";
Blockscad.Msg.DIRECTION_RIGHT = "prawo";
Blockscad.Msg.DIRECTION_TOP = "góra";
Blockscad.Msg.DISABLE_ALL = "Wyłącz Wszystkie Bloki";
Blockscad.Msg.DISCARD_ALL = "Czy skasować %1 bloki?";
Blockscad.Msg.DOCUMENTATION_LINK = "Dokumentacja";
Blockscad.Msg.EMAIL_FIELD = "Adres email";
Blockscad.Msg.ENABLE_ALL = "Włącz Wszystkie Bloki";
Blockscad.Msg.ERROR_BAD_PASSWORD = "Incorrect password - please retype your original password.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_EMPTY = "Please enter an email address.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_INVALID = "Podaj prawidłowy adres emial.";
Blockscad.Msg.ERROR_LOGIN_FAILED = "Nieprawidłowa nazawa użytkownika lub hasło.";
Blockscad.Msg.ERROR_MESSAGE = "Błąd";
Blockscad.Msg.ERROR_MISSING_EMAIL = "We can't find this email address.";  // untranslated
Blockscad.Msg.ERROR_MISSING_USERNAME = "We can't find this username.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_CONFIRM = "Oba hasła muszą być jednakowe.";
Blockscad.Msg.ERROR_PASSWORD_IS_EMPTY = "Please choose a password at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_PASSWORD = "Your password cannot be the word 'password'.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_USERNAME = "Nazwa użytkownika i hasło muszą być rożne!";
Blockscad.Msg.ERROR_PASSWORD_LENGTH = "Your password must be at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_USERNAME_CHARACTERS = "Your username may only contain letters, numbers, -, and _";  // untranslated
Blockscad.Msg.ERROR_USERNAME_EXISTS = "Upss! Taki użytkownik już jest zarejestrowany.";
Blockscad.Msg.ERROR_USERNAME_IS_EMPTY = "Podaj nazwę użytkownika.";
Blockscad.Msg.ERROR_USERNAME_LENGTH = "Username must be between 3 and 30 characters.";  // untranslated
Blockscad.Msg.EXAMPLES_MENU = "Przykłady";
Blockscad.Msg.EXAMPLE_ANTHIAS_FISH = "ryba (Papużak afrykański)";
Blockscad.Msg.EXAMPLE_CUBE_WITH_CUTOUTS = "sześcian z wycięciami";
Blockscad.Msg.EXAMPLE_LOOP_SINE = "sinusoida z pętlą";
Blockscad.Msg.EXAMPLE_LOOP_SUN = "słońce z pętli";
Blockscad.Msg.EXAMPLE_PARAMETRIC_BOX = "pudełko ze zmiennych";
Blockscad.Msg.EXAMPLE_PARAMETRIC_EQ_KNOT = "węzeł z równiania parametrycznego";
Blockscad.Msg.FACES = "ściany";
Blockscad.Msg.FANCYMIRROR_TOOLTIP = "Odbija obiekt/y względem płaszczyzny wyznaczonej miedzy (0,0,0) a punktem (x,y,z).";
Blockscad.Msg.FANCYROTATE_TOOLTIP = "Obraca obiekt/y względem prostej wyznaczonej między (0,0,0) a punktem (x,y,z).";
Blockscad.Msg.FN_TOOLTIP = "Ustal ilość segmentów które zostaną użyte do tworzenia łuków (dla kul, cylindrów, okręgów i torusów).";
Blockscad.Msg.FONT_NAME = "czcionka";
Blockscad.Msg.FONT_SIZE = "rozmiar";
Blockscad.Msg.GENERATE_STL = "Wygeneruj";
Blockscad.Msg.GET_STARTED_VIDEO = "Zaczynamy!";
Blockscad.Msg.HEIGHT = "wysokość";
Blockscad.Msg.HELP_MENU = "Pomoc";
Blockscad.Msg.HIGHLIGHT_INSTANCES = "Zaznacz Wszystkie '%1'";
Blockscad.Msg.HSV_COLOR_MODEL = "HSV";
Blockscad.Msg.HULL_TOOLTIP = "Łączy dwa lub więcej obiektów 'zawijając' je razem. Tworzy otoczę wypuklą w około nich.";
Blockscad.Msg.IMPORT_BLOCKS_LOCAL = "Zaimportuj Bloki do Tego Projektu";
Blockscad.Msg.IMPORT_STL = "importuj STL";
Blockscad.Msg.IMPORT_STL_MENU = "Zaimportuj plik STL to Tego Projektu";
Blockscad.Msg.INTERSECTION = "przecięcie";
Blockscad.Msg.INTERSECTION_TOOLTIP = "Tworzy wspólą część (zachodzące na siebie) dwóch lub wielu obiektów.";
Blockscad.Msg.LINEAREXTRUDE_TOOLTIP = "Wytłacza jeden lub wiele obiektów 2D do podanej wysokości uwzględniając zadany skręt. Kształt może być jednocześnie przekształcany względem osi x i y. Dodatkowo można wyśrotkować obiekt względem oryginału.";
Blockscad.Msg.LINEAR_EXTRUDE = "wytłoczenie liniowe";
Blockscad.Msg.LOAD_BLOCKS_LOCAL = "Wczytaj Bloki z Komputera";
Blockscad.Msg.LOGIN_BUTTON = "Logowanie";
Blockscad.Msg.LOGIN_IN_PROGRESS = "Logowanie...";
Blockscad.Msg.LOGOUT_BUTTON = "Wyloguj";
Blockscad.Msg.MINUS = "minus";
Blockscad.Msg.MIRROR = "odbicie";
Blockscad.Msg.MIRROR_ADVANCED = "specjalne odbicie";
Blockscad.Msg.MOUSEOVER_REDO = "Ponów";
Blockscad.Msg.MOUSEOVER_TRASHCAN = "Skasuj wszystkie bloki";
Blockscad.Msg.MOUSEOVER_UNDO = "Cofnij";
Blockscad.Msg.MY_PROJECTS = "Moje Projekty";
Blockscad.Msg.NEW = "Nowy";
Blockscad.Msg.NEW_PASSWORD = "New Password";  // untranslated
Blockscad.Msg.NEW_PROJECT_BUTTON = "Nowy Projekt";
Blockscad.Msg.NOT_CENTERED = "niewyśrodkowane";
Blockscad.Msg.NOT_COMPATIBLE_WITH_OPENSCAD = "Nie zgodne z OpenSCAD";
Blockscad.Msg.OLD_PASSWORD = "Old Password";  // untranslated
Blockscad.Msg.OPTIONS_MENU = "Opcje";
Blockscad.Msg.PALE_COLORS = "Jasny";
Blockscad.Msg.PARSE_IN_PROGRESS = "Przetwarzanie...";
Blockscad.Msg.PARSING_ERROR_ILLEGAL_VALUE = "%1 blok/i mają niedozwolone wartości (ujemne lub zero)";
Blockscad.Msg.PARSING_ERROR_MISSING_FIELDS = "%1 blok/i mają brakujące pola.";
Blockscad.Msg.PASSWORD_FIELD = "Hasło";
Blockscad.Msg.PASSWORD_FORGOT_FIELD = "Przypomnij Hasło";
Blockscad.Msg.PASSWORD_RESET_EMAIL_INSTRUCTIONS = "We've sent an email to the address associated with your account with a link to reset your password. If you don't see it, check your spam folder";  // untranslated
Blockscad.Msg.PASSWORD_RESET_EMAIL_SENT = "Password Reset Email has been Sent";  // untranslated
Blockscad.Msg.PASSWORD_RETYPE_FIELD = "Powtórz Hasło";
Blockscad.Msg.PLUS = "plus";
Blockscad.Msg.PROJECT_LIST_DELETE_BUTTON = "Skasuj";
Blockscad.Msg.PROJECT_LIST_EXIT = "Zamknij Listę";
Blockscad.Msg.PROJECT_LIST_FILTER = "Filtr";
Blockscad.Msg.PROJECT_LIST_LAST_MODIFIED = "Ostatnia Zmiana";
Blockscad.Msg.PROJECT_LIST_MORE_BUTTON = "Więcej";
Blockscad.Msg.PROJECT_MENU = "Projekt";
Blockscad.Msg.PROJECT_NAME = "Nazwa Projektu";
Blockscad.Msg.PROJECT_NAME_DEFAULT = "Bez_Tytułu";
Blockscad.Msg.RADIUS = "promień";
Blockscad.Msg.REACTIVATE_ACCOUNT_EXPLAINED = "Twoje konto zostało wznowione - nie będzie ono usunięte.";
Blockscad.Msg.REACTIVATE_ACCOUNT_TITLE = "Twoje konto nie zostanie usunięte";
Blockscad.Msg.REACTIVATE_BUTTON = "Okay";
Blockscad.Msg.REGISTER_BUTTON = "Zarejestruj się";
Blockscad.Msg.REGISTER_IN_PROGRESS = "Rejestrowanie...";
Blockscad.Msg.REGISTER_NEW_USER = "Zarejestruj Nowego Użytkownika";
Blockscad.Msg.REMOVE_BLOCK_HIGHLIGHTING = "Wyłącz wyróżnienie bloku";
Blockscad.Msg.REMOVE_HIGHLIGHTING_INSTANCES = "Wyłącz wyróżnianie";
Blockscad.Msg.RENDER_BUTTON = "Renderuj";
Blockscad.Msg.RENDER_ERROR_EMPTY = "Nie ma nic do pokazania";
Blockscad.Msg.RENDER_ERROR_MIXED = "Obecne są kształty 2D i 3D. Dopuszczalny jest tylko jeden rodzaj.";
Blockscad.Msg.RENDER_IN_PROGRESS = "Renderowanie...";
Blockscad.Msg.REPORT_ISSUE = "Zgłoś problem";
Blockscad.Msg.RESET_PASSWORD = "Reset Password";  // untranslated
Blockscad.Msg.RESET_PASSWORD_INSTRUCTIONS = "Enter your username or your email and we will send you an email with instructions to reset your password.";  // untranslated
Blockscad.Msg.RESET_PASSWORD_LINK_BUTTON = "Send me a link to reset my password!";  // untranslated
Blockscad.Msg.RESET_VIEW_BUTTON = "Resetuj Widok";
Blockscad.Msg.RGB_COLOR_MODEL = "RGB";
Blockscad.Msg.ROTATE = "obrót";
Blockscad.Msg.ROTATEEXTRUDE_TOOLTIP = "Wytłacza obrotowo jeden lub wiele obiektów 2D względem osi Z, używając podaną ilość segmentów.";
Blockscad.Msg.ROTATE_ADVANCED = "specialny obrót";
Blockscad.Msg.ROTATE_EXTRUDE = "wytłoczenie obrotowe";
Blockscad.Msg.SAVE_BLOCKS_AS_COPY = "Zapisz jako Kopię";
Blockscad.Msg.SAVE_BLOCKS_LOCAL = "Zapisz Bloki na Komputerze";
Blockscad.Msg.SAVE_BUTTON = "Zapisz";
Blockscad.Msg.SAVE_COMPLETE = "Zapisano!";
Blockscad.Msg.SAVE_FAILED = "Błąd zapisu.";
Blockscad.Msg.SAVE_FAILED_PROJECT_NAME = "Nadaj nazwę swojemu projektowi i spróbuj ponownie.";
Blockscad.Msg.SAVE_IN_PROGRESS = "Zapisywanie...";
Blockscad.Msg.SAVE_PROMPT = "Czy chcesz zapisać swój projekt?";
Blockscad.Msg.SAVE_PROMPT_NO = "Nie zapisuj";
Blockscad.Msg.SAVE_PROMPT_YES = "Zapisz";
Blockscad.Msg.SAVE_SCAD_LOCAL = "Zapisz kod OpenSCAD na Komputerze";
Blockscad.Msg.SCALE = "skala";
Blockscad.Msg.SCALE_TOOLTIP = "Przekształca (zmniejsza/powiększa) obiekt/y o daną wartość w przestrzeni x, y, i z.";
Blockscad.Msg.SIDES = "ściany";
Blockscad.Msg.SIMPLEMIRROR_TOOLTIP = "Odbija obiekt/y względem wyznaczonej płaszczyzny.";
Blockscad.Msg.SIMPLEROTATE_TOOLTIP = "Obraca obiekt/y względem wyznaczonej osi x, y i z.";
Blockscad.Msg.SIMPLE_TOOLBOX = "Proste Narzeędzia";
Blockscad.Msg.SPHERE = "Kula";
Blockscad.Msg.SPHERE_TOOLTIP = "<img src='imgs/en/sphere.svg' width='65'>";
Blockscad.Msg.SQUARE = "kwadrat";
Blockscad.Msg.SQUARE_TOOLTIP = "<img src='imgs/en/square.svg' width='65'>";
Blockscad.Msg.STL_IMPORT_WARNING = "Plik STL nie został zapisany z twoimi blokami.";
Blockscad.Msg.TAPER = "rozciągnij";
Blockscad.Msg.TAPER_TOOLTIP = "Przekształca (zmieniejsza/powiększa) obiekt wzdłóż osi. Najmniejsza wartość to 1, największą ustala użytkownik wpisując w pole wartości.";
Blockscad.Msg.TEXT_DEFAULT_VALUE = "abc";
Blockscad.Msg.TEXT_THICKNESS = "grubość";
Blockscad.Msg.TORUS = "torus";
Blockscad.Msg.TORUS_TOOLTIP = "<img src='imgs/en/torus.svg' width='250px'>";
Blockscad.Msg.TRANSLATE = "translate";  // untranslated
Blockscad.Msg.TRANSLATE_TOOLTIP = "Przenosi obiekt/y do wyznaczonego położenia x, y i z.";
Blockscad.Msg.TWIST = "skręt";
Blockscad.Msg.UNION = "połącz";
Blockscad.Msg.UNION_TOOLTIP = "Łączy dwa lub więcej obiektów.";
Blockscad.Msg.USERNAME_FIELD = "Nazwa użytkownika";
Blockscad.Msg.VARIABLES_BUMPED_ONE = "%1 variable blocks were displaced due to type mismatches";  // untranslated
Blockscad.Msg.VARIABLES_BUMPED_TWO = "variable '%1': type changed from %2 to %3";  // untranslated
Blockscad.Msg.WARNING_RELOAD_STL = "Uwaga: załaduj ponownie blok pliku STL";
Blockscad.Msg.WITH = "i";
Blockscad.Msg.ZOOM_IN_BUTTON = "Przybliż";
Blockscad.Msg.ZOOM_OUT_BUTTON = "Oddal";
Blockscad.Msg.ZOOM_RESET_BUTTON = "Zresetuj widok";
