// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockscad.Msg.ru');


Blockscad.Msg.ABORT_BUTTON = "Прервать";
Blockscad.Msg.ABOUT_LINK = "О компании";
Blockscad.Msg.ACROSS = "через";
Blockscad.Msg.ADVANCED_TOOLBOX = "Полная панель инструментов";
Blockscad.Msg.ALONG = "вдоль";
Blockscad.Msg.AROUND = "вокруг";
Blockscad.Msg.AXES_BUTTON = "Переключить отображение осей";
Blockscad.Msg.AXIS = "ось";
Blockscad.Msg.BLOCKS_BUMPED_OUT_DIMENSIONS = "%1 смещение блоков: 2D и 3D фигуры не могут быть вместе";
Blockscad.Msg.BLOCKS_BUMPED_OUT_TYPES = "%1 смещение блоков: несоответствие типов между числами и логическими значениями";
Blockscad.Msg.BLOCKS_TAB = "Блоки";
Blockscad.Msg.BLOCK_COLORS = "Цветовая палитра";
Blockscad.Msg.BLOCK_TEXT_2D = "2D текст";
Blockscad.Msg.BLOCK_TEXT_3D = "3D текст";
Blockscad.Msg.BROWSE = "просмотр";
Blockscad.Msg.BS_3DTEXT_TOOLTIP = "Изображение объемного текста заданныx шрифта, размера и толщины(3D)";
Blockscad.Msg.BS_TEXT_TOOLTIP = "Изображение текста заданного размера и шрифта на плоскости(2D)";
Blockscad.Msg.CATEGORY_2D_SHAPES = "2D Фигуры";
Blockscad.Msg.CATEGORY_3D_SHAPES = "3D Фигуры";
Blockscad.Msg.CATEGORY_LOGIC = "Логические операции";
Blockscad.Msg.CATEGORY_LOOPS = "Циклы";
Blockscad.Msg.CATEGORY_MATH = "Математика";
Blockscad.Msg.CATEGORY_PROCEDURES = "Модули";
Blockscad.Msg.CATEGORY_SET_OPERATIONS = "Операции над множествами";
Blockscad.Msg.CATEGORY_TEXT = "Текст";
Blockscad.Msg.CATEGORY_TRANSFORMATIONS = "Преобразования";
Blockscad.Msg.CATEGORY_VARIBLES = "Переменные";
Blockscad.Msg.CENTER = "центр";
Blockscad.Msg.CENTERED = "в центре";
Blockscad.Msg.CHANGE_EMAIL = "Change Email";  // untranslated
Blockscad.Msg.CHANGE_EMAIL_CURRENT = "Current Email";  // untranslated
Blockscad.Msg.CHANGE_EMAIL_NEW = "New Email";  // untranslated
Blockscad.Msg.CHANGE_PASSWORD = "Change Password";  // untranslated
Blockscad.Msg.CHANGE_PASSWORD_INSTRUCTIONS = "After changing your password, BlocksCAD will prompt you to login again.";  // untranslated
Blockscad.Msg.CIRCLE = "круг";
Blockscad.Msg.CIRCLE_TOOLTIP = "<img src='imgs/en/circle.svg' width='140'>";
Blockscad.Msg.CLASSIC_COLORS = "Классическая";
Blockscad.Msg.CODE_TAB = "Код";
Blockscad.Msg.COLOR = "цвет";
Blockscad.Msg.COLOR_HSV_TOOLTIP = "'Закрашивает 3D объект в цвет, определяемый тоном, насыщенностью и яркостью в HSV цветовой модели. Значение каждой компоненты определяется от 0 до 100.";
Blockscad.Msg.COLOR_HUE = "тон";
Blockscad.Msg.COLOR_RGB_TOOLTIP = "Закрашивает 3D объект в цвет, определяемый красной, синей и зеленой компонентами RGB цветовой модели. Значение каждой компоненты определяется от 0 до 100.";
Blockscad.Msg.COLOR_SATURATION = "насыщенность";
Blockscad.Msg.COLOR_TOOLTIP = "Закрашивает 3D объект в указанный цвет.";
Blockscad.Msg.COLOR_VALUE = "яркость";
Blockscad.Msg.CONFIRM_DIALOG_NO = "Отмена";
Blockscad.Msg.CONFIRM_DIALOG_YES = "Да";
Blockscad.Msg.CONFIRM_NEW_PASSWORD = "Retype New Password";
Blockscad.Msg.CONTROLS_FOR_TOOLTIP_CHAINHULL = "В каждой итерации цикла применяется операция 'выпуклая оболочка' ";
Blockscad.Msg.CONVEX_HULL = "выпуклая оболочка";
Blockscad.Msg.CUBE = "куб";
Blockscad.Msg.CUBE_TOOLTIP = "<img src='imgs/en/cube.svg' width='100px'>";
Blockscad.Msg.CYLINDER = "цилиндр";
Blockscad.Msg.CYLINDER_TOOLTIP = "<img src='imgs/en/cylinder.svg' width='190px'>";
Blockscad.Msg.DEFAULT_COLOR_BUTTON = "Установить цвет отрисовки по умолчанию";
Blockscad.Msg.DELETE_ACCOUNT = "Delete My Account";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_BUTTON = "Delete Account and Sign Out";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM = "Are you sure you want to delete your BlocksCAD account?";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM_PASSWORD = "Enter password to confirm";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_ONE = "In about 48 hours your account will be permanently deleted.";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_TWO = "If you change your mind, just sign in to your account within the next 48 hours.";  // untranslated
Blockscad.Msg.DELETE_PROJECT_CONFIRM = "Вы уверены, что хотите удалить * Project_name *?";
Blockscad.Msg.DIALOG_OR = "или";
Blockscad.Msg.DIAMETER = "диаметр";
Blockscad.Msg.DIFFERENCE = "разница";
Blockscad.Msg.DIFFERENCE_TOOLTIP = "Вычитает один или более обЪектов из первого объекта в списке.";
Blockscad.Msg.DIRECTION_BACK = "вид сзади";
Blockscad.Msg.DIRECTION_BOTTOM = "низ";
Blockscad.Msg.DIRECTION_DIAGONAL = "диагональ";
Blockscad.Msg.DIRECTION_FRONT = "перед";
Blockscad.Msg.DIRECTION_LEFT = "вид слева";
Blockscad.Msg.DIRECTION_RIGHT = "вид справа";
Blockscad.Msg.DIRECTION_TOP = "верх";
Blockscad.Msg.DISABLE_ALL = "Отключить все блоки";
Blockscad.Msg.DISCARD_ALL = "Удалить %1 блока(ов)?";
Blockscad.Msg.DOCUMENTATION_LINK = "Документация";
Blockscad.Msg.EMAIL_FIELD = "Адрес электронной почты";
Blockscad.Msg.ENABLE_ALL = "Подключить все блоки";
Blockscad.Msg.ERROR_BAD_PASSWORD = "Incorrect password - please retype your original password.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_EMPTY = "Please enter an email address.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_INVALID = "Вы должны предоставить действующий адрес электронной почты.";
Blockscad.Msg.ERROR_LOGIN_FAILED = "Неправильное имя пользователя или пароль.";
Blockscad.Msg.ERROR_MESSAGE = "Ошибка";
Blockscad.Msg.ERROR_MISSING_EMAIL = "We can't find this email address.";  // untranslated
Blockscad.Msg.ERROR_MISSING_USERNAME = "We can't find this username.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_CONFIRM = "Ваш второй пароль должен совпадать с первым паролем.";
Blockscad.Msg.ERROR_PASSWORD_IS_EMPTY = "Please choose a password at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_PASSWORD = "Your password cannot be the word 'password'.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_USERNAME = "Ваш пароль не совпадает с вашим именем пользователя!";
Blockscad.Msg.ERROR_PASSWORD_LENGTH = "Your password must be at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_USERNAME_CHARACTERS = "Your username may only contain letters, numbers, -, and _";  // untranslated
Blockscad.Msg.ERROR_USERNAME_EXISTS = "Извините, это имя пользователя уже существует.";
Blockscad.Msg.ERROR_USERNAME_IS_EMPTY = "Пожалуйста, выберите имя пользователя.";
Blockscad.Msg.ERROR_USERNAME_LENGTH = "Username must be between 3 and 30 characters.";  // untranslated
Blockscad.Msg.EXAMPLES_MENU = "Примеры";
Blockscad.Msg.EXAMPLE_ANTHIAS_FISH = "тропическая рыбка";
Blockscad.Msg.EXAMPLE_CUBE_WITH_CUTOUTS = "куб с прорезями";
Blockscad.Msg.EXAMPLE_LOOP_SINE = "sine function with loop";  // untranslated
Blockscad.Msg.EXAMPLE_LOOP_SUN = "sun: пример применения циклов";
Blockscad.Msg.EXAMPLE_PARAMETRIC_BOX = "коробка универсального размера";
Blockscad.Msg.EXAMPLE_PARAMETRIC_EQ_KNOT = "узел: применение параметрических уравнений";
Blockscad.Msg.FACES = "грани";
Blockscad.Msg.FANCYMIRROR_TOOLTIP = "Зеркально отображает один или несколько объектов в плоскости, чей вектор нормали к плоскости задан координатами в точках (0,0,0) и (x,y,z).";
Blockscad.Msg.FANCYROTATE_TOOLTIP = "Вращает один или несколько объектов вокруг вектора с координатами (0,0,0) и (x,y,z)";
Blockscad.Msg.FN_TOOLTIP = "Устанавливает число сторон, используемых для замены дуг(в сфере, цилиндре, окружности и торе) на хорды(отрезки).";
Blockscad.Msg.FONT_NAME = "шрифт";
Blockscad.Msg.FONT_SIZE = "размер";
Blockscad.Msg.GENERATE_STL = "Создать";
Blockscad.Msg.GET_STARTED_VIDEO = "Начать!";
Blockscad.Msg.HEIGHT = "высота";
Blockscad.Msg.HELP_MENU = "Помощь";
Blockscad.Msg.HIGHLIGHT_INSTANCES = "Подсветить '%1' примеры";
Blockscad.Msg.HSV_COLOR_MODEL = "HSV цветовая модель";
Blockscad.Msg.HULL_TOOLTIP = "Объединяет один или несколько объектов, «обвертывая», 'оборачивая' их вместе в 'пленку'.";
Blockscad.Msg.IMPORT_BLOCKS_LOCAL = "Импортировать блоки в текущий проект";
Blockscad.Msg.IMPORT_STL = "загрузка STL файла";
Blockscad.Msg.IMPORT_STL_MENU = "Импортировать STL файл в текущий проект";
Blockscad.Msg.INTERSECTION = "пересечение";
Blockscad.Msg.INTERSECTION_TOOLTIP = "Результат этой операции--область пересечения двух или более объектов.";
Blockscad.Msg.LINEAREXTRUDE_TOOLTIP = "Выдавливает один или несколько двумерных объектов на заданную высоту с заданным углом вращения. Объект может быть масштабирован по осям x и y.";
Blockscad.Msg.LINEAR_EXTRUDE = "линейная экструзия";
Blockscad.Msg.LOAD_BLOCKS_LOCAL = "Загрузить блоки с компьютера";
Blockscad.Msg.LOGIN_BUTTON = "Вход";
Blockscad.Msg.LOGIN_IN_PROGRESS = "Вход в систему...";
Blockscad.Msg.LOGOUT_BUTTON = "Выйти";
Blockscad.Msg.MINUS = "минус";
Blockscad.Msg.MIRROR = "отображение";
Blockscad.Msg.MIRROR_ADVANCED = "Нестандартное отображение";
Blockscad.Msg.MOUSEOVER_REDO = "Вернуть последнюю редакцию";
Blockscad.Msg.MOUSEOVER_TRASHCAN = "Удалить все блоки";
Blockscad.Msg.MOUSEOVER_UNDO = "Отменить редакцию";
Blockscad.Msg.MY_PROJECTS = "Мои Проекты";
Blockscad.Msg.NEW = "Новый Проект";
Blockscad.Msg.NEW_PASSWORD = "New Password";  // untranslated
Blockscad.Msg.NEW_PROJECT_BUTTON = "Новый проект";
Blockscad.Msg.NOT_CENTERED = "не в центре";
Blockscad.Msg.NOT_COMPATIBLE_WITH_OPENSCAD = "Не совместимо с OpenSCAD";
Blockscad.Msg.OLD_PASSWORD = "Old Password";  // untranslated
Blockscad.Msg.OPTIONS_MENU = "Настройки";
Blockscad.Msg.PALE_COLORS = "Светлая";
Blockscad.Msg.PARSE_IN_PROGRESS = "Анализ...";
Blockscad.Msg.PARSING_ERROR_ILLEGAL_VALUE = "%1 Недопустимые значения (отрицательное или нулевое) в блоках";
Blockscad.Msg.PARSING_ERROR_MISSING_FIELDS = "%1 В блоках пропущены обязательные поля.";
Blockscad.Msg.PASSWORD_FIELD = "Пароль";
Blockscad.Msg.PASSWORD_FORGOT_FIELD = "Забыли пароль?";
Blockscad.Msg.PASSWORD_RESET_EMAIL_INSTRUCTIONS = "We've sent an email to the address associated with your account with a link to reset your password. If you don't see it, check your spam folder";  // untranslated
Blockscad.Msg.PASSWORD_RESET_EMAIL_SENT = "Password Reset Email has been Sent";  // untranslated
Blockscad.Msg.PASSWORD_RETYPE_FIELD = "Введите пароль еще раз";
Blockscad.Msg.PLUS = "плюс";
Blockscad.Msg.PROJECT_LIST_DELETE_BUTTON = "Удалить";
Blockscad.Msg.PROJECT_LIST_EXIT = "Выйыи из списка";
Blockscad.Msg.PROJECT_LIST_FILTER = "Фильтры";
Blockscad.Msg.PROJECT_LIST_LAST_MODIFIED = "Последнее изменение";
Blockscad.Msg.PROJECT_LIST_MORE_BUTTON = "Дополнительно";
Blockscad.Msg.PROJECT_MENU = "Проект";
Blockscad.Msg.PROJECT_NAME = "Название проекта";
Blockscad.Msg.PROJECT_NAME_DEFAULT = "Без названия";
Blockscad.Msg.RADIUS = "радиус";
Blockscad.Msg.REACTIVATE_ACCOUNT_EXPLAINED = "Ваш аккаунт активирован - он не будет удален.";
Blockscad.Msg.REACTIVATE_ACCOUNT_TITLE = "Ваш аккаунт не будет удален.";
Blockscad.Msg.REACTIVATE_BUTTON = "Okay";
Blockscad.Msg.REGISTER_BUTTON = "Регистрация";
Blockscad.Msg.REGISTER_IN_PROGRESS = "Registering...";
Blockscad.Msg.REGISTER_NEW_USER = "Регистрация нового пользователя";
Blockscad.Msg.REMOVE_BLOCK_HIGHLIGHTING = "Удалить подсветку блока";
Blockscad.Msg.REMOVE_HIGHLIGHTING_INSTANCES = "Удалить подсветку";
Blockscad.Msg.RENDER_BUTTON = "Рендер";
Blockscad.Msg.RENDER_ERROR_EMPTY = "Отсутствует код для отрисовки";
Blockscad.Msg.RENDER_ERROR_MIXED = "В коде одновременно присутствуют 2D и 3D объекты. Возможно присутствие только одного вида.";
Blockscad.Msg.RENDER_IN_PROGRESS = "Отрисовка...";
Blockscad.Msg.REPORT_ISSUE = "Сообщить о проблеме";
Blockscad.Msg.RESET_PASSWORD = "Reset Password";  // untranslated
Blockscad.Msg.RESET_PASSWORD_INSTRUCTIONS = "Enter your username or your email and we will send you an email with instructions to reset your password.";  // untranslated
Blockscad.Msg.RESET_PASSWORD_LINK_BUTTON = "Send me a link to reset my password!";  // untranslated
Blockscad.Msg.RESET_VIEW_BUTTON = "Сброс настроек";
Blockscad.Msg.RGB_COLOR_MODEL = "RGB цветовая модель";
Blockscad.Msg.ROTATE = "вращение";
Blockscad.Msg.ROTATEEXTRUDE_TOOLTIP = "Выдавливает с вращением вокруг оси Z один или несколько двумерных объектов. Необходимо указать число сторон трехмерной фигуры.";
Blockscad.Msg.ROTATE_ADVANCED = "Нестандартное вращение";
Blockscad.Msg.ROTATE_EXTRUDE = "вращательная экструзия";
Blockscad.Msg.SAVE_BLOCKS_AS_COPY = "Сохранить как копию";
Blockscad.Msg.SAVE_BLOCKS_LOCAL = "Сохранить блоки на компьютере";
Blockscad.Msg.SAVE_BUTTON = "Сохранить";
Blockscad.Msg.SAVE_COMPLETE = "Сохранено!";
Blockscad.Msg.SAVE_FAILED = "Невозможно сохранить.";
Blockscad.Msg.SAVE_FAILED_PROJECT_NAME = "Пожалуйста, дайте имя(название) вашему проекту, затем попробуйте снова.";
Blockscad.Msg.SAVE_IN_PROGRESS = "Сохраняется...";
Blockscad.Msg.SAVE_PROMPT = "Вы хотите сохранить свой проект?";
Blockscad.Msg.SAVE_PROMPT_NO = "Не сохранять";
Blockscad.Msg.SAVE_PROMPT_YES = "Сохранить";
Blockscad.Msg.SAVE_SCAD_LOCAL = "Сохранить OpenSCAD код на компьютере";
Blockscad.Msg.SCALE = "масштаб";
Blockscad.Msg.SCALE_TOOLTIP = "Масштабирует один или несколько объектов на указанное значение в осям x, y и z.";
Blockscad.Msg.SIDES = "стороны";
Blockscad.Msg.SIMPLEMIRROR_TOOLTIP = "Отображает один или несколько объектов в указанной плоскости.";
Blockscad.Msg.SIMPLEROTATE_TOOLTIP = "Вращает один или несколько объектов вокруг осей x, y и z на указанные углы.";
Blockscad.Msg.SIMPLE_TOOLBOX = "Базовая панель инструментов";
Blockscad.Msg.SPHERE = "сфера";
Blockscad.Msg.SPHERE_TOOLTIP = "<img src='imgs/en/sphere.svg' width='140'>";
Blockscad.Msg.SQUARE = "квадрат";
Blockscad.Msg.SQUARE_TOOLTIP = "<img src='imgs/en/square.svg' width='65'>";
Blockscad.Msg.STL_IMPORT_WARNING = "STL файлы не сохранятся с вашими блоками.";
Blockscad.Msg.TAPER = "сужение";
Blockscad.Msg.TAPER_TOOLTIP = "Масштабирует объект вдоль заданной оси. Наименьшее значение -- единица, а наибольшее значение задается пользователем.";
Blockscad.Msg.TEXT_DEFAULT_VALUE = "абв";
Blockscad.Msg.TEXT_THICKNESS = "толщина";
Blockscad.Msg.TORUS = "тор";
Blockscad.Msg.TORUS_TOOLTIP = "<img src='imgs/en/torus.svg' width='540px'>";
Blockscad.Msg.TRANSLATE = "перенос";
Blockscad.Msg.TRANSLATE_TOOLTIP = "Переносит один или несколько объектов по осям x, y и z на указанные значения.";
Blockscad.Msg.TWIST = "скручивание";
Blockscad.Msg.UNION = "объединение";
Blockscad.Msg.UNION_TOOLTIP = "Объединяет два и более объектов.";
Blockscad.Msg.USERNAME_FIELD = "Имя пользователя";
Blockscad.Msg.VARIABLES_BUMPED_ONE = "%1 блоки переменных были смещены из-за несоответствия типов";
Blockscad.Msg.VARIABLES_BUMPED_TWO = "переменная '% 1': тип изменен с% 2 на% 3";
Blockscad.Msg.WARNING_RELOAD_STL = "Предупреждение: перезагрузите файл STL";
Blockscad.Msg.WITH = "с";
Blockscad.Msg.ZOOM_IN_BUTTON = "Увеличить";
Blockscad.Msg.ZOOM_OUT_BUTTON = "Уменьшить";
Blockscad.Msg.ZOOM_RESET_BUTTON = "Сброс изображения";
