// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockscad.Msg.sv');


Blockscad.Msg.ABORT_BUTTON = "Avbryt";
Blockscad.Msg.ABOUT_LINK = "Om";
Blockscad.Msg.ACROSS = "över";
Blockscad.Msg.ADVANCED_TOOLBOX = "Avancerad Verktygslåda";
Blockscad.Msg.ALONG = "längs";
Blockscad.Msg.AROUND = "runt";
Blockscad.Msg.AXES_BUTTON = "Växla mellan axlarna";
Blockscad.Msg.AXIS = "axel";
Blockscad.Msg.BLOCKS_BUMPED_OUT_DIMENSIONS = "%1 anropsblock var förskjutna: 2D och 3D-former kan inte vara tillsammans";
Blockscad.Msg.BLOCKS_BUMPED_OUT_TYPES = "%1 anropsblock förskjutet: felmatchning av typ mellan %2 och %3";
Blockscad.Msg.BLOCKS_TAB = "Block";
Blockscad.Msg.BLOCK_COLORS = "Block Färgscheman";
Blockscad.Msg.BLOCK_TEXT_2D = "2D text";  // untranslated
Blockscad.Msg.BLOCK_TEXT_3D = "3D text";  // untranslated
Blockscad.Msg.BROWSE = "bläddra";
Blockscad.Msg.BS_3DTEXT_TOOLTIP = "En 3D-framställning utav text med en given storlek, typsnitt och tjocklek";
Blockscad.Msg.BS_TEXT_TOOLTIP = "En 2D-framställning utav text med en given storlek och typsnitt";
Blockscad.Msg.CATEGORY_2D_SHAPES = "2D former";
Blockscad.Msg.CATEGORY_3D_SHAPES = "3D former";
Blockscad.Msg.CATEGORY_LOGIC = "Logik";
Blockscad.Msg.CATEGORY_LOOPS = "Loopar";
Blockscad.Msg.CATEGORY_MATH = "Matematik";
Blockscad.Msg.CATEGORY_PROCEDURES = "Moduler";
Blockscad.Msg.CATEGORY_SET_OPERATIONS = "Ange Ops";
Blockscad.Msg.CATEGORY_TEXT = "Text";
Blockscad.Msg.CATEGORY_TRANSFORMATIONS = "Omvandlingar";
Blockscad.Msg.CATEGORY_VARIBLES = "Variablar";
Blockscad.Msg.CENTER = "centrum";
Blockscad.Msg.CENTERED = "centrerad";
Blockscad.Msg.CHANGE_EMAIL = "Change Email";  // untranslated
Blockscad.Msg.CHANGE_EMAIL_CURRENT = "Current Email";  // untranslated
Blockscad.Msg.CHANGE_EMAIL_NEW = "New Email";  // untranslated
Blockscad.Msg.CHANGE_PASSWORD = "Change Password";  // untranslated
Blockscad.Msg.CHANGE_PASSWORD_INSTRUCTIONS = "After changing your password, BlocksCAD will prompt you to login again.";  // untranslated
Blockscad.Msg.CIRCLE = "cirkel";
Blockscad.Msg.CIRCLE_TOOLTIP = "<img src='imgs/en/circle.svg' width='65'>";
Blockscad.Msg.CLASSIC_COLORS = "Klassisk";
Blockscad.Msg.CODE_TAB = "Kod";
Blockscad.Msg.COLOR = "färg";
Blockscad.Msg.COLOR_HSV_TOOLTIP = "Applicera en färg genom att ange färgton, mättnad och värdekomponenter. Varje värde bör vara mellan 0 och 100.";
Blockscad.Msg.COLOR_HUE = "nyans";
Blockscad.Msg.COLOR_RGB_TOOLTIP = "Apply a color by specifying the red, blue, and green components.  Each value should be between 0 and 100.";  // untranslated
Blockscad.Msg.COLOR_SATURATION = "mättnad";
Blockscad.Msg.COLOR_TOOLTIP = "Applicerar färg till barnobjektet, vilket måste vara 3D.";
Blockscad.Msg.COLOR_VALUE = "värde";
Blockscad.Msg.CONFIRM_DIALOG_NO = "Annullera";
Blockscad.Msg.CONFIRM_DIALOG_YES = "ja'visst";
Blockscad.Msg.CONFIRM_NEW_PASSWORD = "Confirm New Password";  // untranslated
Blockscad.Msg.CONTROLS_FOR_TOOLTIP_CHAINHULL = "Returnera det konvexa höljet utav varje form i slingan med nästa form";
Blockscad.Msg.CONVEX_HULL = "hölja";
Blockscad.Msg.CUBE = "kub";
Blockscad.Msg.CUBE_TOOLTIP = "<img src='imgs/en/cube.svg' width='100px'>";
Blockscad.Msg.CYLINDER = "cylinder";
Blockscad.Msg.CYLINDER_TOOLTIP = "<img src='imgs/en/cylinder.svg' width='90px'>";
Blockscad.Msg.DEFAULT_COLOR_BUTTON = "Ange standard framställningsfärg";
Blockscad.Msg.DELETE_ACCOUNT = "Delete My Account";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_BUTTON = "Delete Account and Sign Out";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM = "Are you sure you want to delete your BlocksCAD account?";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM_PASSWORD = "Enter password to confirm";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_ONE = "In about 48 hours your account will be permanently deleted.";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_TWO = "If you change your mind, just sign in to your account within the next 48 hours.";  // untranslated
Blockscad.Msg.DELETE_PROJECT_CONFIRM = "Är du säker på att du vill radera *Project_name*?";
Blockscad.Msg.DIALOG_OR = "eller";
Blockscad.Msg.DIAMETER = "diameter";
Blockscad.Msg.DIFFERENCE = "skillnad";
Blockscad.Msg.DIFFERENCE_TOOLTIP = "Subtraherar ett eller flera objekt från det första objektet i listan.";
Blockscad.Msg.DIRECTION_BACK = "bakåt";
Blockscad.Msg.DIRECTION_BOTTOM = "botten";
Blockscad.Msg.DIRECTION_DIAGONAL = "diagonal";
Blockscad.Msg.DIRECTION_FRONT = "framsida";
Blockscad.Msg.DIRECTION_LEFT = "vänster";
Blockscad.Msg.DIRECTION_RIGHT = "höger";
Blockscad.Msg.DIRECTION_TOP = "ovansida";
Blockscad.Msg.DISABLE_ALL = "Inaktivera alla block";
Blockscad.Msg.DISCARD_ALL = "Ta bort alla %1 block?";
Blockscad.Msg.DOCUMENTATION_LINK = "Dokumentation";
Blockscad.Msg.EMAIL_FIELD = "E-postadress";
Blockscad.Msg.ENABLE_ALL = "Aktivera alla block";
Blockscad.Msg.ERROR_BAD_PASSWORD = "Incorrect password - please retype your original password.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_EMPTY = "Please enter an email address.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_INVALID = "Du måste ange en giltig e-postadress.";
Blockscad.Msg.ERROR_LOGIN_FAILED = "Felaktigt användarnamn eller lösenord.";
Blockscad.Msg.ERROR_MESSAGE = "Fel";
Blockscad.Msg.ERROR_MISSING_EMAIL = "We can't find this email address.";  // untranslated
Blockscad.Msg.ERROR_MISSING_USERNAME = "We can't find this username.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_CONFIRM = "Ditt andra lösenord måste matcha det första lösenordet.";
Blockscad.Msg.ERROR_PASSWORD_IS_EMPTY = "Please choose a password at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_PASSWORD = "Your password cannot be the word 'password'.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_USERNAME = "Ditt lösenord kan inte matcha ditt användarnamn!";
Blockscad.Msg.ERROR_PASSWORD_LENGTH = "Your password must be at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_USERNAME_CHARACTERS = "Your username may only contain letters, numbers, -, and _";  // untranslated
Blockscad.Msg.ERROR_USERNAME_EXISTS = "Tyvärr är det användarnamnet redan taget.";
Blockscad.Msg.ERROR_USERNAME_IS_EMPTY = "Vänligen välj ett användarnamn.";
Blockscad.Msg.ERROR_USERNAME_LENGTH = "Username must be between 3 and 30 characters.";  // untranslated
Blockscad.Msg.EXAMPLES_MENU = "Exempel";
Blockscad.Msg.EXAMPLE_ANTHIAS_FISH = "anthias fisk";
Blockscad.Msg.EXAMPLE_CUBE_WITH_CUTOUTS = "kub med utklipp";
Blockscad.Msg.EXAMPLE_LOOP_SINE = "sinusfunktion med slinga";
Blockscad.Msg.EXAMPLE_LOOP_SUN = "sol gjord med slinga";
Blockscad.Msg.EXAMPLE_PARAMETRIC_BOX = "vilken storlek som helst";
Blockscad.Msg.EXAMPLE_PARAMETRIC_EQ_KNOT = "knut från parametriska ekvationer";
Blockscad.Msg.FACES = "sidor2";
Blockscad.Msg.FANCYMIRROR_TOOLTIP = "Speglar ett eller flera objekt över det angivna planet vars normala vektor är från (0,0,0) till punkten (x, y, z).";
Blockscad.Msg.FANCYROTATE_TOOLTIP = "Roterar ett eller flera objekt runt en vektor från ursprunget (0,0,0) till punkten (x, y, z)";
Blockscad.Msg.FN_TOOLTIP = "Ställer in antalet sidor som används för att approximera bågar (i sfären, cylindern, cirkeln och torusen).";
Blockscad.Msg.FONT_NAME = "typsnitt";
Blockscad.Msg.FONT_SIZE = "storlek";
Blockscad.Msg.GENERATE_STL = "Generera";
Blockscad.Msg.GET_STARTED_VIDEO = "Kom igång!";
Blockscad.Msg.HEIGHT = "höjd";
Blockscad.Msg.HELP_MENU = "Hjälp";
Blockscad.Msg.HIGHLIGHT_INSTANCES = "Markera '%1' Instanser";
Blockscad.Msg.HSV_COLOR_MODEL = "HSV";
Blockscad.Msg.HULL_TOOLTIP = "Kombinerar ett eller flera objekt genom att 'packa' ihop dem i ett hölj.";
Blockscad.Msg.IMPORT_BLOCKS_LOCAL = "Importera block till nuvarande projekt";
Blockscad.Msg.IMPORT_STL = "STL importering";
Blockscad.Msg.IMPORT_STL_MENU = "Importera STL fil till nuvarande projekt";
Blockscad.Msg.INTERSECTION = "genomskärning";
Blockscad.Msg.INTERSECTION_TOOLTIP = "Returnerar korsningen (område som överlappar) av två eller flera objekt.";
Blockscad.Msg.LINEAREXTRUDE_TOOLTIP = "Extruderar ett eller flera 2-dimensionella objekt med en angiven höjd med en specificerad vridning. Formen kan skalas när den extruderar i både x och y. Det kan eventuellt centreras kring ursprunget.";
Blockscad.Msg.LINEAR_EXTRUDE = "linjär extrudering";
Blockscad.Msg.LOAD_BLOCKS_LOCAL = "Ladda block från din dator";
Blockscad.Msg.LOGIN_BUTTON = "Logga in";
Blockscad.Msg.LOGIN_IN_PROGRESS = "Loggar in...";
Blockscad.Msg.LOGOUT_BUTTON = "Logga ut";
Blockscad.Msg.MINUS = "minus";
Blockscad.Msg.MIRROR = "spegla";
Blockscad.Msg.MIRROR_ADVANCED = "särskild spegling";
Blockscad.Msg.MOUSEOVER_REDO = "Gör om";
Blockscad.Msg.MOUSEOVER_TRASHCAN = "Ta bort alla block";
Blockscad.Msg.MOUSEOVER_UNDO = "Ångra";
Blockscad.Msg.MY_PROJECTS = "Mina projekt";
Blockscad.Msg.NEW = "Nytt";
Blockscad.Msg.NEW_PASSWORD = "New Password";  // untranslated
Blockscad.Msg.NEW_PROJECT_BUTTON = "Nytt projekt";
Blockscad.Msg.NOT_CENTERED = "ej centrerad";
Blockscad.Msg.NOT_COMPATIBLE_WITH_OPENSCAD = "Ej kompatibel med OpenSCAD";
Blockscad.Msg.OLD_PASSWORD = "Old Password";  // untranslated
Blockscad.Msg.OPTIONS_MENU = "Alternativ";
Blockscad.Msg.PALE_COLORS = "Blek";
Blockscad.Msg.PARSE_IN_PROGRESS = "Satslöser...";
Blockscad.Msg.PARSING_ERROR_ILLEGAL_VALUE = "%1 utav blocken har ett illegalt värde (negativt eller noll)";
Blockscad.Msg.PARSING_ERROR_MISSING_FIELDS = "%1 utav blocken saknar fält.";
Blockscad.Msg.PASSWORD_FIELD = "Lösenord";
Blockscad.Msg.PASSWORD_FORGOT_FIELD = "Glömt ditt lösenord?";
Blockscad.Msg.PASSWORD_RESET_EMAIL_INSTRUCTIONS = "We've sent an email to the address associated with your account with a link to reset your password. If you don't see it, check your spam folder";  // untranslated
Blockscad.Msg.PASSWORD_RESET_EMAIL_SENT = "Password Reset Email has been Sent";  // untranslated
Blockscad.Msg.PASSWORD_RETYPE_FIELD = "Skriv in lösenord igen";
Blockscad.Msg.PLUS = "plus";
Blockscad.Msg.PROJECT_LIST_DELETE_BUTTON = "Radera";
Blockscad.Msg.PROJECT_LIST_EXIT = "Avsluta Lista";
Blockscad.Msg.PROJECT_LIST_FILTER = "Filtrera";
Blockscad.Msg.PROJECT_LIST_LAST_MODIFIED = "Senast ändrad";
Blockscad.Msg.PROJECT_LIST_MORE_BUTTON = "Mer";
Blockscad.Msg.PROJECT_MENU = "Projekt";
Blockscad.Msg.PROJECT_NAME = "Projektnamn";
Blockscad.Msg.PROJECT_NAME_DEFAULT = "odöpt";
Blockscad.Msg.RADIUS = "radius";
Blockscad.Msg.REACTIVATE_ACCOUNT_EXPLAINED = "Ditt konto är återaktiverat - det kommer inte längre att raderas.";
Blockscad.Msg.REACTIVATE_ACCOUNT_TITLE = "Ditt konto kommer inte att raderas";
Blockscad.Msg.REACTIVATE_BUTTON = "Okay";  // untranslated
Blockscad.Msg.REGISTER_BUTTON = "Registrera";
Blockscad.Msg.REGISTER_IN_PROGRESS = "Registrering...";
Blockscad.Msg.REGISTER_NEW_USER = "Registrera ny användare";
Blockscad.Msg.REMOVE_BLOCK_HIGHLIGHTING = "Ta bort blockmarkering";
Blockscad.Msg.REMOVE_HIGHLIGHTING_INSTANCES = "Ta bort markering";
Blockscad.Msg.RENDER_BUTTON = "Framställ";
Blockscad.Msg.RENDER_ERROR_EMPTY = "Inget att framställa";
Blockscad.Msg.RENDER_ERROR_MIXED = "Både 2D och 3D-objekt är närvarande. Det kan bara vara en åt gången.";
Blockscad.Msg.RENDER_IN_PROGRESS = "Framställer...";
Blockscad.Msg.REPORT_ISSUE = "Rapportera problem";
Blockscad.Msg.RESET_PASSWORD = "Reset Password";  // untranslated
Blockscad.Msg.RESET_PASSWORD_INSTRUCTIONS = "Enter your username or your email and we will send you an email with instructions to reset your password.";  // untranslated
Blockscad.Msg.RESET_PASSWORD_LINK_BUTTON = "Send me a link to reset my password!";  // untranslated
Blockscad.Msg.RESET_VIEW_BUTTON = "Återställ Vyn";
Blockscad.Msg.RGB_COLOR_MODEL = "RGB";
Blockscad.Msg.ROTATE = "rotera";
Blockscad.Msg.ROTATEEXTRUDE_TOOLTIP = "Rotera extrudering på ett eller flera 2-dimensionella objekt runt Z-axeln med ett specificerat antal sidor.";
Blockscad.Msg.ROTATE_ADVANCED = "särskild rotering";
Blockscad.Msg.ROTATE_EXTRUDE = "rotera extrudering";
Blockscad.Msg.SAVE_BLOCKS_AS_COPY = "Spara som en kopia";
Blockscad.Msg.SAVE_BLOCKS_LOCAL = "Spara block till din dator";
Blockscad.Msg.SAVE_BUTTON = "Spara";
Blockscad.Msg.SAVE_COMPLETE = "Sparad!";
Blockscad.Msg.SAVE_FAILED = "Sparning Misslyckades.";
Blockscad.Msg.SAVE_FAILED_PROJECT_NAME = "Vänligen ge ditt projekt ett namn och försök igen.";
Blockscad.Msg.SAVE_IN_PROGRESS = "Sparar...";
Blockscad.Msg.SAVE_PROMPT = "Vill du spara ditt projekt?";
Blockscad.Msg.SAVE_PROMPT_NO = "Spara inte";
Blockscad.Msg.SAVE_PROMPT_YES = "Spara";
Blockscad.Msg.SAVE_SCAD_LOCAL = "Spara OpenSCAD kod till din dator";
Blockscad.Msg.SCALE = "skala";
Blockscad.Msg.SCALE_TOOLTIP = "Skalar ett eller flera objekt med specificerad mängd i dimensionerna x, y och z.";
Blockscad.Msg.SIDES = "sidor";
Blockscad.Msg.SIMPLEMIRROR_TOOLTIP = "Speglar ett eller flera objekt över ett specificerat plan.";
Blockscad.Msg.SIMPLEROTATE_TOOLTIP = "Roterar ett eller flera objekt runt den angivna axeln x, y och z.";
Blockscad.Msg.SIMPLE_TOOLBOX = "Enkel Verktygslåda";
Blockscad.Msg.SPHERE = "sfär";
Blockscad.Msg.SPHERE_TOOLTIP = "<img src='imgs/en/sphere.svg' width='65'>";
Blockscad.Msg.SQUARE = "fyrkant";
Blockscad.Msg.SQUARE_TOOLTIP = "<img src='imgs/en/square.svg' width='65'>";
Blockscad.Msg.STL_IMPORT_WARNING = "STL-filer sparas inte med dina block.";
Blockscad.Msg.TAPER = "avsmalning";
Blockscad.Msg.TAPER_TOOLTIP = "Skalar formen längs en axel. Det minsta värdet längs väljaxeln är skalad vid ett, och det största värdet är skalat vid användarens ingångsskalningsvärde.";
Blockscad.Msg.TEXT_DEFAULT_VALUE = "abc";
Blockscad.Msg.TEXT_THICKNESS = "tjocklek";
Blockscad.Msg.TORUS = "torus";
Blockscad.Msg.TORUS_TOOLTIP = "<img src='imgs/en/torus.svg' width='540px'>";
Blockscad.Msg.TRANSLATE = "translate";  // untranslated
Blockscad.Msg.TRANSLATE_TOOLTIP = "Translates (moves) one or more objects in specified dimensions x, y, and z.";  // untranslated
Blockscad.Msg.TWIST = "vrida";
Blockscad.Msg.UNION = "gruppera";
Blockscad.Msg.UNION_TOOLTIP = "Combines two or more objects into one.";  // untranslated
Blockscad.Msg.USERNAME_FIELD = "Användarnamn";
Blockscad.Msg.VARIABLES_BUMPED_ONE = "%1 variable blocks were displaced due to type mismatches";  // untranslated
Blockscad.Msg.VARIABLES_BUMPED_TWO = "variabel '%1': typ ändrad från %2 till %3";
Blockscad.Msg.WARNING_RELOAD_STL = "Varning: ladda om ditt STL-filblock";
Blockscad.Msg.WITH = "med";
Blockscad.Msg.ZOOM_IN_BUTTON = "Zooma in";
Blockscad.Msg.ZOOM_OUT_BUTTON = "Zooma ut";
Blockscad.Msg.ZOOM_RESET_BUTTON = "Återställ vy";
