// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockscad.Msg.tr');


Blockscad.Msg.ABORT_BUTTON = "İptal";
Blockscad.Msg.ABOUT_LINK = "Hakkında";
Blockscad.Msg.ACROSS = "karşısına";
Blockscad.Msg.ADVANCED_TOOLBOX = "Gelişmiş Malzeme Kutusu";
Blockscad.Msg.ALONG = "boyunca";
Blockscad.Msg.AROUND = "etrafında";
Blockscad.Msg.AXES_BUTTON = "Eksen ekranını değiştir";
Blockscad.Msg.AXIS = "eksen";
Blockscad.Msg.BLOCKS_BUMPED_OUT_DIMENSIONS = "%1 çağrı blokunun yeri değiştirildi: iki boyutlu ve üç boyutlu şekiller bir arada bulunamaz";
Blockscad.Msg.BLOCKS_BUMPED_OUT_TYPES = "%1 çağrı blokunun yeri değiştirildi: %2 ile %3 arasında tür uyumsuzluğu";
Blockscad.Msg.BLOCKS_TAB = "Bloklar";
Blockscad.Msg.BLOCK_COLORS = "Blok Renk Grubu";
Blockscad.Msg.BLOCK_TEXT_2D = "iki boyutlu metin";
Blockscad.Msg.BLOCK_TEXT_3D = "üç boyutlu metin";
Blockscad.Msg.BROWSE = "göz at";
Blockscad.Msg.BS_3DTEXT_TOOLTIP = "Belirli boyut, yazı tipi ve kalınlıktaki metnin üç boyutlu görüntüsü";
Blockscad.Msg.BS_TEXT_TOOLTIP = "Belirli boyut ve yazı tipindeki metnin iki boyutlu görüntüsü";
Blockscad.Msg.CATEGORY_2D_SHAPES = "İki Boyutlu Şekiller";
Blockscad.Msg.CATEGORY_3D_SHAPES = "Üç Boyutlu Şekiller";
Blockscad.Msg.CATEGORY_LOGIC = "Mantık";
Blockscad.Msg.CATEGORY_LOOPS = "Döngüler";
Blockscad.Msg.CATEGORY_MATH = "Matematik";
Blockscad.Msg.CATEGORY_PROCEDURES = "Modüller";
Blockscad.Msg.CATEGORY_SET_OPERATIONS = "Küme İşlemleri";
Blockscad.Msg.CATEGORY_TEXT = "Metin";
Blockscad.Msg.CATEGORY_TRANSFORMATIONS = "Dönüşümler";
Blockscad.Msg.CATEGORY_VARIBLES = "Değişkenler";
Blockscad.Msg.CENTER = "merkez";
Blockscad.Msg.CENTERED = "merkezlenmiş";
Blockscad.Msg.CHANGE_EMAIL = "Change Email";  // untranslated
Blockscad.Msg.CHANGE_EMAIL_CURRENT = "Current Email";  // untranslated
Blockscad.Msg.CHANGE_EMAIL_NEW = "New Email";  // untranslated
Blockscad.Msg.CHANGE_PASSWORD = "Şifre değiştir";
Blockscad.Msg.CHANGE_PASSWORD_INSTRUCTIONS = "After changing your password, BlocksCAD will prompt you to login again.";  // untranslated
Blockscad.Msg.CIRCLE = "çember";
Blockscad.Msg.CIRCLE_TOOLTIP = "<img src='imgs/en/circle.svg' width='65'>";
Blockscad.Msg.CLASSIC_COLORS = "Klasik";
Blockscad.Msg.CODE_TAB = "Kod";
Blockscad.Msg.COLOR = "renk";
Blockscad.Msg.COLOR_HSV_TOOLTIP = "Renk tonu, doygunluk ve değer bileşenlerini belirterek renk uygula. Her değer 0 ile 100 arasında olmalıdır.";
Blockscad.Msg.COLOR_HUE = "renk tonu";
Blockscad.Msg.COLOR_RGB_TOOLTIP = "Kırmızı, mavi, yeşil bileşenlerini belirterek renk uygula. Her değer 0 ile 100 arasında olmalıdır.";
Blockscad.Msg.COLOR_SATURATION = "doygunluk";
Blockscad.Msg.COLOR_TOOLTIP = "Üç boyutlu olması gereken alt nesneye renk uygular.";
Blockscad.Msg.COLOR_VALUE = "değer";
Blockscad.Msg.CONFIRM_DIALOG_NO = "Vazgeç";
Blockscad.Msg.CONFIRM_DIALOG_YES = "Evet";
Blockscad.Msg.CONFIRM_NEW_PASSWORD = "Şifrenizi yeniden yazın";
Blockscad.Msg.CONTROLS_FOR_TOOLTIP_CHAINHULL = "Döngüdeki her şeklin dışbükey gövdesini bir sonraki şekil ile döndür";
Blockscad.Msg.CONVEX_HULL = "gövde";
Blockscad.Msg.CUBE = "küp";
Blockscad.Msg.CUBE_TOOLTIP = "<img src='imgs/en/cube.svg' width='100px'>";
Blockscad.Msg.CYLINDER = "silindir";
Blockscad.Msg.CYLINDER_TOOLTIP = "<img src='imgs/en/cylinder.svg' width='90px'>";
Blockscad.Msg.DEFAULT_COLOR_BUTTON = "Varsayılan görüntü rengini ayarla";
Blockscad.Msg.DELETE_ACCOUNT = "Delete My Account";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_BUTTON = "Delete Account and Sign Out";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM = "Are you sure you want to delete your BlocksCAD account?";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_CONFIRM_PASSWORD = "Enter password to confirm";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_ONE = "In about 48 hours your account will be permanently deleted.";  // untranslated
Blockscad.Msg.DELETE_ACCOUNT_INSTRUCTIONS_TWO = "If you change your mind, just sign in to your account within the next 48 hours.";  // untranslated
Blockscad.Msg.DELETE_PROJECT_CONFIRM = "*Project_name* projesini silmek istediğinize emin misiniz?";
Blockscad.Msg.DIALOG_OR = "veya";
Blockscad.Msg.DIAMETER = "çap";
Blockscad.Msg.DIFFERENCE = "fark";
Blockscad.Msg.DIFFERENCE_TOOLTIP = "Listedeki ilk nesneden bir veya daha fazla nesneyi çıkarır.";
Blockscad.Msg.DIRECTION_BACK = "arkadan";
Blockscad.Msg.DIRECTION_BOTTOM = "alttan";
Blockscad.Msg.DIRECTION_DIAGONAL = "çapraz";
Blockscad.Msg.DIRECTION_FRONT = "önden";
Blockscad.Msg.DIRECTION_LEFT = "soldan";
Blockscad.Msg.DIRECTION_RIGHT = "sağdan";
Blockscad.Msg.DIRECTION_TOP = "üstten";
Blockscad.Msg.DISABLE_ALL = "Tüm Blokları Devre Dışı Bırak";
Blockscad.Msg.DISCARD_ALL = "%1 blokun tamamı silinsin mi?";
Blockscad.Msg.DOCUMENTATION_LINK = "Belgeleme";
Blockscad.Msg.EMAIL_FIELD = "E-posta Adresi";
Blockscad.Msg.ENABLE_ALL = "Tüm Blokları Etkinleştir";
Blockscad.Msg.ERROR_BAD_PASSWORD = "Incorrect password - please retype your original password.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_EMPTY = "Please enter an email address.";  // untranslated
Blockscad.Msg.ERROR_EMAIL_IS_INVALID = "Geçerli bir e-posta adresi sağlamalısınız.";
Blockscad.Msg.ERROR_LOGIN_FAILED = "Yanlış kullanıcı adı veya şifre.";
Blockscad.Msg.ERROR_MESSAGE = "Hata";
Blockscad.Msg.ERROR_MISSING_EMAIL = "We can't find this email address.";  // untranslated
Blockscad.Msg.ERROR_MISSING_USERNAME = "We can't find this username.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_CONFIRM = "İkinci girdiğiniz şifre ilk şifreyle eşleşmelidir";
Blockscad.Msg.ERROR_PASSWORD_IS_EMPTY = "Please choose a password at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_PASSWORD = "Your password cannot be the word 'password'.";  // untranslated
Blockscad.Msg.ERROR_PASSWORD_IS_USERNAME = "Şifreniz kullanıcı adınızla aynı olamaz!";
Blockscad.Msg.ERROR_PASSWORD_LENGTH = "Your password must be at least 6 characters long.";  // untranslated
Blockscad.Msg.ERROR_USERNAME_CHARACTERS = "Your username may only contain letters, numbers, -, and _";  // untranslated
Blockscad.Msg.ERROR_USERNAME_EXISTS = "Üzgünüz, bu kullanıcı adı zaten var.";
Blockscad.Msg.ERROR_USERNAME_IS_EMPTY = "Lütfen bir kullanıcı adı seçin.";
Blockscad.Msg.ERROR_USERNAME_LENGTH = "Username must be between 3 and 30 characters.";  // untranslated
Blockscad.Msg.EXAMPLES_MENU = "Örnekler";
Blockscad.Msg.EXAMPLE_ANTHIAS_FISH = "berber balığı";
Blockscad.Msg.EXAMPLE_CUBE_WITH_CUTOUTS = "kesikli küp";
Blockscad.Msg.EXAMPLE_LOOP_SINE = "döngülü sinüs işlevi";
Blockscad.Msg.EXAMPLE_LOOP_SUN = "döngüyle oluşturulmuş güneş";
Blockscad.Msg.EXAMPLE_PARAMETRIC_BOX = "her boyutta kutu";
Blockscad.Msg.EXAMPLE_PARAMETRIC_EQ_KNOT = "parametrik denklemlerle oluşturulmuş düğüm";
Blockscad.Msg.FACES = "yüzler";
Blockscad.Msg.FANCYMIRROR_TOOLTIP = "Bir veya daha fazla nesneyi normal vektörü (0,0,0)’dan (x,y,z) noktasına kadar olan belirtilen düzlemin karşısına yansıtır.";
Blockscad.Msg.FANCYROTATE_TOOLTIP = "Bir veya daha fazla nesneyi orijinden (0,0,0) (x,y,z) noktasına kadar olan vektör etrafında döndürür.";
Blockscad.Msg.FN_TOOLTIP = "(Küre, silindir, çember ve simitte) yayları yaklaştırmak için kullanılan kenarların sayısını ayarlar.";
Blockscad.Msg.FONT_NAME = "yazı tipi";
Blockscad.Msg.FONT_SIZE = "boyut";
Blockscad.Msg.GENERATE_STL = "Oluştur";
Blockscad.Msg.GET_STARTED_VIDEO = "Başla!";
Blockscad.Msg.HEIGHT = "yükseklik";
Blockscad.Msg.HELP_MENU = "Yardım";
Blockscad.Msg.HIGHLIGHT_INSTANCES = "'%1' Örneklerini Vurgula";
Blockscad.Msg.HSV_COLOR_MODEL = "HSV";
Blockscad.Msg.HULL_TOOLTIP = "Bir veya daha fazla nesneyi bir gövdeye 'sararak' birleştirir.";
Blockscad.Msg.IMPORT_BLOCKS_LOCAL = "Mevcut Projeye Blok Aktar";
Blockscad.Msg.IMPORT_STL = "STL aktar";
Blockscad.Msg.IMPORT_STL_MENU = "Mevcut Projeye STL Dosyası Aktar";
Blockscad.Msg.INTERSECTION = "kesişme";
Blockscad.Msg.INTERSECTION_TOOLTIP = "İki veya daha fazla nesnenin kesişimini (üst üste gelen alanını) döndürür.";
Blockscad.Msg.LINEAREXTRUDE_TOOLTIP = "Bir veya daha fazla iki boyutlu nesneyi belirtilen yükseklik ve kıvrım ile yükseltir. Şekil hem x hem y’de yükseldiği için ölçeklendirilebilir. Tercihen orijini merkezine alabilir.";
Blockscad.Msg.LINEAR_EXTRUDE = "doğrusal yükselt";
Blockscad.Msg.LOAD_BLOCKS_LOCAL = "Blokları Bilgisayarından Yükle";
Blockscad.Msg.LOGIN_BUTTON = "Giriş";
Blockscad.Msg.LOGIN_IN_PROGRESS = "Giriş yapılıyor...";
Blockscad.Msg.LOGOUT_BUTTON = "Çıkış";
Blockscad.Msg.MINUS = "eksi";
Blockscad.Msg.MIRROR = "yansıt";
Blockscad.Msg.MIRROR_ADVANCED = "gelişmiş yansıtma";
Blockscad.Msg.MOUSEOVER_REDO = "Yinele";
Blockscad.Msg.MOUSEOVER_TRASHCAN = "Tüm blokları sil";
Blockscad.Msg.MOUSEOVER_UNDO = "Geri Al";
Blockscad.Msg.MY_PROJECTS = "Projelerim";
Blockscad.Msg.NEW = "Yeni";
Blockscad.Msg.NEW_PASSWORD = "Yeni şifre";
Blockscad.Msg.NEW_PROJECT_BUTTON = "Yeni Proje";
Blockscad.Msg.NOT_CENTERED = "merkezlenmemiş";
Blockscad.Msg.NOT_COMPATIBLE_WITH_OPENSCAD = "OpenSCAD ile uyumlu değil";
Blockscad.Msg.OLD_PASSWORD = "Eski parola";
Blockscad.Msg.OPTIONS_MENU = "Seçenekler";
Blockscad.Msg.PALE_COLORS = "Soluk";
Blockscad.Msg.PARSE_IN_PROGRESS = "Ayrıştırılıyor...";
Blockscad.Msg.PARSING_ERROR_ILLEGAL_VALUE = "%1 blok geçersiz değer içeriyor (negatif veya sıfır)";
Blockscad.Msg.PARSING_ERROR_MISSING_FIELDS = "%1 blokta eksik alanlar var.";
Blockscad.Msg.PASSWORD_FIELD = "Şifre";
Blockscad.Msg.PASSWORD_FORGOT_FIELD = "Şifrenizi mi unuttunuz?";
Blockscad.Msg.PASSWORD_RESET_EMAIL_INSTRUCTIONS = "We've sent an email to the address associated with your account with a link to reset your password. If you don't see it, check your spam folder";  // untranslated
Blockscad.Msg.PASSWORD_RESET_EMAIL_SENT = "Password Reset Email has been Sent";  // untranslated
Blockscad.Msg.PASSWORD_RETYPE_FIELD = "Şifrenizi yeniden yazın";
Blockscad.Msg.PLUS = "artı";
Blockscad.Msg.PROJECT_LIST_DELETE_BUTTON = "Sil";
Blockscad.Msg.PROJECT_LIST_EXIT = "Listeden Çık";
Blockscad.Msg.PROJECT_LIST_FILTER = "Filtrele";
Blockscad.Msg.PROJECT_LIST_LAST_MODIFIED = "Son Değiştirme";
Blockscad.Msg.PROJECT_LIST_MORE_BUTTON = "Daha Fazla";
Blockscad.Msg.PROJECT_MENU = "Proje";
Blockscad.Msg.PROJECT_NAME = "Proje Adı";
Blockscad.Msg.PROJECT_NAME_DEFAULT = "Adsız";
Blockscad.Msg.RADIUS = "yarıçap";
Blockscad.Msg.REACTIVATE_ACCOUNT_EXPLAINED = "Hesabınız yeniden etkinleştirildi – artık silinmeyecek.";
Blockscad.Msg.REACTIVATE_ACCOUNT_TITLE = "Hesabınız silinmeyecek";
Blockscad.Msg.REACTIVATE_BUTTON = "Okay";
Blockscad.Msg.REGISTER_BUTTON = "Kaydol";
Blockscad.Msg.REGISTER_IN_PROGRESS = "Kaydınız yapılıyor...";
Blockscad.Msg.REGISTER_NEW_USER = "Yeni Kullanıcı Kaydet";
Blockscad.Msg.REMOVE_BLOCK_HIGHLIGHTING = "Blok vurgulamasını kaldır";
Blockscad.Msg.REMOVE_HIGHLIGHTING_INSTANCES = "Vurgulamayı kaldır";
Blockscad.Msg.RENDER_BUTTON = "İşle";
Blockscad.Msg.RENDER_ERROR_EMPTY = "İşlenecek Şekil Yok";
Blockscad.Msg.RENDER_ERROR_MIXED = "İki boyutlu ve üç boyutlu nesneler aynı anda mevcut. Yalnızca biri olabilir.";
Blockscad.Msg.RENDER_IN_PROGRESS = "İşleniyor...";
Blockscad.Msg.REPORT_ISSUE = "Sorun Bildir";
Blockscad.Msg.RESET_PASSWORD = "Şifre değiştir";
Blockscad.Msg.RESET_PASSWORD_INSTRUCTIONS = "Enter your username or your email and we will send you an email with instructions to reset your password.";  // untranslated
Blockscad.Msg.RESET_PASSWORD_LINK_BUTTON = "Send me a link to reset my password!";  // untranslated
Blockscad.Msg.RESET_VIEW_BUTTON = "Görünümü Sıfırla";
Blockscad.Msg.RGB_COLOR_MODEL = "RGB";
Blockscad.Msg.ROTATE = "döndür";
Blockscad.Msg.ROTATEEXTRUDE_TOOLTIP = "Bir veya daha fazla iki boyutlu nesneyi belirtilen kenar sayısı ile Z ekseni etrafında döndürerek yükseltir.";
Blockscad.Msg.ROTATE_ADVANCED = "gelişmiş döndürme";
Blockscad.Msg.ROTATE_EXTRUDE = "döndürerek yükselt";
Blockscad.Msg.SAVE_BLOCKS_AS_COPY = "Kopya Olarak Kaydet";
Blockscad.Msg.SAVE_BLOCKS_LOCAL = "Blokları Bilgisayarına Kaydet";
Blockscad.Msg.SAVE_BUTTON = "Kaydet";
Blockscad.Msg.SAVE_COMPLETE = "Kaydedildi!";
Blockscad.Msg.SAVE_FAILED = "Kaydetme Başarısız.";
Blockscad.Msg.SAVE_FAILED_PROJECT_NAME = "Lütfen projenize bir isim verip tekrar deneyin.";
Blockscad.Msg.SAVE_IN_PROGRESS = "Kaydediliyor...";
Blockscad.Msg.SAVE_PROMPT = "Projenizi kaydetmek istiyor musunuz?";
Blockscad.Msg.SAVE_PROMPT_NO = "Kaydetme";
Blockscad.Msg.SAVE_PROMPT_YES = "Kaydet";
Blockscad.Msg.SAVE_SCAD_LOCAL = "OpenSCAD Kodunu Bilgisayarına Kaydet";
Blockscad.Msg.SCALE = "ölçeklendir";
Blockscad.Msg.SCALE_TOOLTIP = "Bir veya daha fazla nesneyi x, y, z boyutlarında belirtilen miktarda ölçeklendirir.";
Blockscad.Msg.SIDES = "kenarlar";
Blockscad.Msg.SIMPLEMIRROR_TOOLTIP = "Bir veya daha fazla nesneyi belirtilen düzlemin karşısına yansıtır.";
Blockscad.Msg.SIMPLEROTATE_TOOLTIP = "Bir veya daha fazla nesneyi belirtilen x, y, z eksenleri etrafında döndürür.";
Blockscad.Msg.SIMPLE_TOOLBOX = "Basit Malzeme Kutusu";
Blockscad.Msg.SPHERE = "küre";
Blockscad.Msg.SPHERE_TOOLTIP = "<img src='imgs/en/sphere.svg' width='65'>";
Blockscad.Msg.SQUARE = "kare";
Blockscad.Msg.SQUARE_TOOLTIP = "<img src='imgs/en/square.svg' width='65'>";
Blockscad.Msg.STL_IMPORT_WARNING = "STL dosyaları bloklarınızla birlikte kaydedilmedi.";
Blockscad.Msg.TAPER = "sivrilt";
Blockscad.Msg.TAPER_TOOLTIP = "Şekli bir eksen boyunca ölçeklendirir. Seçili eksen boyunca en küçük değer bire ölçeklenir, en büyük değer kullanıcı girdisi ölçek değerine ölçeklenir.";
Blockscad.Msg.TEXT_DEFAULT_VALUE = "abc";
Blockscad.Msg.TEXT_THICKNESS = "kalınlık";
Blockscad.Msg.TORUS = "simit";
Blockscad.Msg.TORUS_TOOLTIP = "<img src='imgs/en/torus.svg' width='250px'>";
Blockscad.Msg.TRANSLATE = "ötele";
Blockscad.Msg.TRANSLATE_TOOLTIP = "Bir veya daha fazla nesneyi belirtilen x, y, z boyutlarında öteler (hareket ettirir).";
Blockscad.Msg.TWIST = "kıvır";
Blockscad.Msg.UNION = "birleşme";
Blockscad.Msg.UNION_TOOLTIP = "İki veya daha fazla nesneyi tek parça hâlinde birleştirir.";
Blockscad.Msg.USERNAME_FIELD = "Kullanıcı Adı";
Blockscad.Msg.VARIABLES_BUMPED_ONE = "Tür uyumsuzluklarından dolayı %1 değişken blokunun yeri değiştirildi";
Blockscad.Msg.VARIABLES_BUMPED_TWO = "'%1' değişkeni: türü %2’den %3’e çevrildi";
Blockscad.Msg.WARNING_RELOAD_STL = "Uyarı: STL dosyası blokunuzu yeniden yükleyin";
Blockscad.Msg.WITH = "ile";
Blockscad.Msg.ZOOM_IN_BUTTON = "Yakınlaştır";
Blockscad.Msg.ZOOM_OUT_BUTTON = "Uzaklaştır";
Blockscad.Msg.ZOOM_RESET_BUTTON = "Görünümü sıfırla";
